import type { ProductCategory, ProductIndustry } from "@/lib/products";

export type CatalogRoadmapItem = {
  name: string;
  category: ProductCategory;
  componentType: string;
  buyerFit: ProductIndustry[];
  role: string;
  note: string;
};

export const catalogRoadmapItems: CatalogRoadmapItem[] = [
  {
    name: "AMD Ryzen 9 9950X",
    category: "CPUs",
    componentType: "Desktop CPU",
    buyerFit: ["Other"],
    role: "High-end consumer CPU for local AI workstations and creator PCs.",
    note: "Verify motherboard, cooling, and PCIe lane needs before standardizing.",
  },
  {
    name: "AMD Threadripper PRO 7995WX",
    category: "CPUs",
    componentType: "Workstation CPU",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Large workstation CPU for multi-GPU builds, memory-heavy workloads, and engineering teams.",
    note: "Best treated as a high-budget platform choice, not a casual desktop upgrade.",
  },
  {
    name: "AMD EPYC 9654",
    category: "CPUs",
    componentType: "Server CPU",
    buyerFit: ["Manufacturing", "Transportation & Logistics"],
    role: "Server CPU for private inference servers, virtualization, and high-memory local AI infrastructure.",
    note: "Confirm server board, memory channel, and chassis compatibility.",
  },
  {
    name: "Intel Core Ultra 9 285K",
    category: "CPUs",
    componentType: "Desktop CPU",
    buyerFit: ["Other", "Retail"],
    role: "Modern desktop CPU option for balanced local AI workstations with GPU acceleration.",
    note: "NPU marketing is less important than GPU, memory, thermals, and software stack.",
  },
  {
    name: "Intel Xeon W9-3595X",
    category: "CPUs",
    componentType: "Workstation CPU",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Enterprise workstation CPU for ECC memory, expansion, and professional AI hardware builds.",
    note: "Useful when reliability and PCIe expansion matter more than lowest cost.",
  },
  {
    name: "Ampere Altra Max M128-30",
    category: "CPUs",
    componentType: "ARM server CPU",
    buyerFit: ["Other"],
    role: "ARM server CPU for efficient infrastructure experiments and non-CUDA service layers.",
    note: "Treat as a specialist option unless the software stack is ARM-ready.",
  },
  {
    name: "NVIDIA GeForce RTX 4090",
    category: "GPUs & Accelerators",
    componentType: "Consumer GPU",
    buyerFit: ["Other", "Manufacturing"],
    role: "High-performance single-GPU baseline for local LLMs, vision models, and image generation.",
    note: "Still a strong value if pricing is reasonable and power/cooling are handled.",
  },
  {
    name: "NVIDIA GeForce RTX 5090",
    category: "GPUs & Accelerators",
    componentType: "Consumer GPU",
    buyerFit: ["Other", "Manufacturing"],
    role: "Newer single-GPU path for local AI buyers who want current-generation CUDA support.",
    note: "Pricing and availability should be manually verified before recommending.",
  },
  {
    name: "NVIDIA RTX PRO 6000 Blackwell",
    category: "GPUs & Accelerators",
    componentType: "Workstation GPU",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Large-memory professional GPU for single-card local AI systems and workstation inference.",
    note: "High-budget option where memory, ECC, and supportability matter.",
  },
  {
    name: "NVIDIA RTX 6000 Ada",
    category: "GPUs & Accelerators",
    componentType: "Workstation GPU",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Professional GPU for stable workstation deployments with more VRAM than consumer cards.",
    note: "Compare used/new pricing against newer Blackwell workstation cards.",
  },
  {
    name: "NVIDIA GeForce RTX 4060 Ti 16GB",
    category: "GPUs & Accelerators",
    componentType: "Budget GPU",
    buyerFit: ["Other", "Retail"],
    role: "Low-power 16GB card for budget local AI, smaller models, and starter systems.",
    note: "Good VRAM-per-watt, but not a high-throughput card.",
  },
  {
    name: "NVIDIA GeForce RTX 4070 Ti Super",
    category: "GPUs & Accelerators",
    componentType: "Consumer GPU",
    buyerFit: ["Other"],
    role: "Balanced local AI and creator GPU for users who want more speed than budget cards.",
    note: "Watch VRAM limits before positioning it for larger models.",
  },
  {
    name: "NVIDIA GeForce RTX 4080 Super",
    category: "GPUs & Accelerators",
    componentType: "Consumer GPU",
    buyerFit: ["Other"],
    role: "High-end local AI card for image generation, small serving, and fast single-user inference.",
    note: "Often speed-rich but memory-limited compared with 24GB and 48GB cards.",
  },
  {
    name: "NVIDIA L40S",
    category: "GPUs & Accelerators",
    componentType: "Data center GPU",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Data center GPU for inference servers, visualization, and enterprise AI infrastructure.",
    note: "Requires proper server airflow, power, and procurement validation.",
  },
  {
    name: "NVIDIA H100 PCIe",
    category: "GPUs & Accelerators",
    componentType: "Data center GPU",
    buyerFit: ["Healthcare", "Manufacturing"],
    role: "Enterprise accelerator for serious private inference and training workloads.",
    note: "Usually belongs in server architecture, not DIY workstations.",
  },
  {
    name: "NVIDIA H200 SXM",
    category: "GPUs & Accelerators",
    componentType: "Data center GPU",
    buyerFit: ["Healthcare", "Manufacturing"],
    role: "High-memory accelerator for enterprise-scale model serving and large-context workloads.",
    note: "Procurement, cooling, and chassis ecosystem must be verified.",
  },
  {
    name: "AMD Radeon PRO W7900",
    category: "GPUs & Accelerators",
    componentType: "Workstation GPU",
    buyerFit: ["Manufacturing", "Other"],
    role: "48GB professional GPU option for buyers exploring non-NVIDIA local AI paths.",
    note: "Software compatibility should be validated for each runtime.",
  },
  {
    name: "AMD Radeon AI PRO R9700",
    category: "GPUs & Accelerators",
    componentType: "Workstation GPU",
    buyerFit: ["Manufacturing", "Other"],
    role: "Modern AMD AI workstation card candidate for open and ROCm-aligned deployments.",
    note: "Availability, drivers, and runtime maturity should be verified.",
  },
  {
    name: "Intel Arc Pro B60 24GB",
    category: "GPUs & Accelerators",
    componentType: "Workstation GPU",
    buyerFit: ["Other", "Retail"],
    role: "Affordable high-VRAM GPU candidate for non-CUDA experimentation and edge workstations.",
    note: "Treat as promising but software-stack dependent.",
  },
  {
    name: "Google Coral USB Accelerator",
    category: "GPUs & Accelerators",
    componentType: "Edge TPU",
    buyerFit: ["Retail", "Manufacturing"],
    role: "Small accelerator for low-power TensorFlow Lite edge inference.",
    note: "Best for compact models, not modern LLM workloads.",
  },
  {
    name: "Arduino Nicla Vision",
    category: "Boards, SBCs & Microcontrollers",
    componentType: "TinyML vision board",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "TinyML board for compact vision, sensor fusion, and low-power inspection concepts.",
    note: "Best for learning and constrained embedded use cases.",
  },
  {
    name: "Arduino Portenta H7",
    category: "Boards, SBCs & Microcontrollers",
    componentType: "Industrial microcontroller",
    buyerFit: ["Manufacturing", "Other"],
    role: "Industrial-grade microcontroller board for control loops and edge prototypes.",
    note: "Useful in automation stacks that need deterministic control.",
  },
  {
    name: "Arduino Portenta X8",
    category: "Boards, SBCs & Microcontrollers",
    componentType: "Linux-capable industrial board",
    buyerFit: ["Manufacturing", "Other"],
    role: "Hybrid microcontroller/Linux board for secure industrial edge applications.",
    note: "Position for buyers needing more than a basic microcontroller.",
  },
  {
    name: "Raspberry Pi Pico 2 W",
    category: "Boards, SBCs & Microcontrollers",
    componentType: "Microcontroller board",
    buyerFit: ["Other"],
    role: "Low-cost wireless microcontroller for sensors, control, and educational edge projects.",
    note: "Tiny price point makes it valuable for parts-volume content.",
  },
  {
    name: "Espressif ESP32-S3-DevKitC-1",
    category: "Boards, SBCs & Microcontrollers",
    componentType: "Wireless MCU dev kit",
    buyerFit: ["Retail", "Agriculture", "Other"],
    role: "Wi-Fi/Bluetooth microcontroller for connected sensors, low-cost cameras, and edge nodes.",
    note: "A strong building block for inexpensive connected products.",
  },
  {
    name: "STMicroelectronics STM32 Nucleo-H743ZI2",
    category: "Boards, SBCs & Microcontrollers",
    componentType: "MCU development board",
    buyerFit: ["Manufacturing", "Other"],
    role: "High-performance MCU development board for industrial control and embedded AI experiments.",
    note: "Good for serious embedded developers rather than casual beginners.",
  },
  {
    name: "PJRC Teensy 4.1",
    category: "Boards, SBCs & Microcontrollers",
    componentType: "Microcontroller board",
    buyerFit: ["Other"],
    role: "Fast microcontroller board for real-time audio, signal processing, and compact control systems.",
    note: "Useful in DIY and prototyping guides.",
  },
  {
    name: "Luxonis OAK-D Pro",
    category: "Cameras & Vision",
    componentType: "Depth AI camera",
    buyerFit: ["Retail", "Manufacturing"],
    role: "Stereo depth camera with onboard AI for spatial perception.",
    note: "Good for robotics, retail analytics, and safety zones.",
  },
  {
    name: "Luxonis OAK-D Lite",
    category: "Cameras & Vision",
    componentType: "Depth AI camera",
    buyerFit: ["Other", "Retail"],
    role: "Lower-cost OAK-D option for spatial AI experiments and prototypes.",
    note: "Good starter recommendation for depth AI buyers.",
  },
  {
    name: "Intel RealSense D455",
    category: "Cameras & Vision",
    componentType: "Depth camera",
    buyerFit: ["Manufacturing", "Retail", "Healthcare"],
    role: "Depth camera for spatial analytics, robotics perception, and measurement.",
    note: "Already covered and worth keeping as a comparison point.",
  },
  {
    name: "Basler ace 2",
    category: "Cameras & Vision",
    componentType: "Industrial camera",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Industrial camera family for repeatable machine vision capture.",
    note: "Ideal for quality inspection buyer journeys.",
  },
  {
    name: "FLIR Boson+",
    category: "Cameras & Vision",
    componentType: "Thermal camera module",
    buyerFit: ["Agriculture", "Transportation & Logistics", "Healthcare"],
    role: "Thermal module for night vision, condition monitoring, and environment-aware sensing.",
    note: "Specialized but high-value when thermal data matters.",
  },
  {
    name: "Raspberry Pi AI Camera",
    category: "Cameras & Vision",
    componentType: "AI camera module",
    buyerFit: ["Other", "Retail"],
    role: "Low-cost camera module with onboard AI sensor capabilities for Raspberry Pi projects.",
    note: "Important for hobbyist and education traffic.",
  },
  {
    name: "Arducam ToF Camera",
    category: "Cameras & Vision",
    componentType: "Time-of-flight camera",
    buyerFit: ["Other", "Manufacturing"],
    role: "Compact depth camera for range sensing and robotics experiments.",
    note: "Good bridge between hobby and practical edge projects.",
  },
  {
    name: "Stereolabs ZED 2i",
    category: "Cameras & Vision",
    componentType: "Stereo depth camera",
    buyerFit: ["Other", "Manufacturing"],
    role: "Rugged stereo camera for robotics, spatial mapping, and 3D perception.",
    note: "Use in robotics comparisons, and consider adding Robotics as a future buyer segment.",
  },
  {
    name: "IDS uEye+ XCP",
    category: "Cameras & Vision",
    componentType: "Industrial camera",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Compact industrial camera family for machine vision and embedded systems.",
    note: "Useful for expanding beyond Basler in vision comparisons.",
  },
  {
    name: "Bosch BME688",
    category: "Sensors",
    componentType: "Environmental sensor",
    buyerFit: ["Retail", "Healthcare", "Manufacturing"],
    role: "Gas, humidity, pressure, and temperature sensor for environmental intelligence.",
    note: "Small part with many edge AI context uses.",
  },
  {
    name: "Bosch BMI270",
    category: "Sensors",
    componentType: "IMU sensor",
    buyerFit: ["Healthcare", "Other"],
    role: "Motion sensor for wearables, activity recognition, and compact device telemetry.",
    note: "Good for TinyML and physical AI content.",
  },
  {
    name: "Sensirion SCD41",
    category: "Sensors",
    componentType: "CO2 sensor",
    buyerFit: ["Retail", "Healthcare", "Manufacturing"],
    role: "CO2 sensor for indoor air quality and occupancy-aware systems.",
    note: "Useful in smart building and facility monitoring bundles.",
  },
  {
    name: "Sensirion SHT45",
    category: "Sensors",
    componentType: "Humidity and temperature sensor",
    buyerFit: ["Agriculture", "Healthcare", "Retail"],
    role: "Accurate temperature/humidity sensing for environment-aware deployments.",
    note: "Strong commodity sensor candidate for small parts monetization.",
  },
  {
    name: "ST VL53L8CX",
    category: "Sensors",
    componentType: "Time-of-flight sensor",
    buyerFit: ["Retail", "Other"],
    role: "Multizone distance sensor for proximity, occupancy, and compact spatial systems.",
    note: "Useful for low-cost spatial awareness kits.",
  },
  {
    name: "TDK InvenSense ICM-42688-P",
    category: "Sensors",
    componentType: "IMU sensor",
    buyerFit: ["Other", "Transportation & Logistics"],
    role: "Motion sensor for robotics, vibration, and mobile device telemetry.",
    note: "Good for robotics and drone accessory lists.",
  },
  {
    name: "Stevens HydraProbe",
    category: "Sensors",
    componentType: "Soil sensor",
    buyerFit: ["Agriculture"],
    role: "Soil moisture and salinity sensor for precision agriculture deployments.",
    note: "Already aligned with agriculture catalog strategy.",
  },
  {
    name: "Banner Q45CT Current Sensor",
    category: "Sensors",
    componentType: "Industrial current sensor",
    buyerFit: ["Manufacturing"],
    role: "Current sensing for machine monitoring and predictive maintenance.",
    note: "Good fit for manufacturing solution kits.",
  },
  {
    name: "SICK TiM781 LiDAR",
    category: "Sensors",
    componentType: "2D LiDAR",
    buyerFit: ["Manufacturing", "Transportation & Logistics"],
    role: "LiDAR sensor for object detection, safety zones, and mobile robotics.",
    note: "High-value sensor category for physical AI deployments.",
  },
  {
    name: "NVIDIA ConnectX-7",
    category: "Networking & Connectivity",
    componentType: "Network adapter",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "High-speed networking card for GPU clusters and AI servers.",
    note: "Also belongs in local AI systems; use tags later for multi-category discovery.",
  },
  {
    name: "NVIDIA ConnectX-6 Dx",
    category: "Networking & Connectivity",
    componentType: "Network adapter",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Data center networking card for secure, high-throughput AI infrastructure.",
    note: "Useful lower-cost option in used server builds.",
  },
  {
    name: "NVIDIA BlueField-3 DPU",
    category: "Networking & Connectivity",
    componentType: "DPU",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "DPU for networking, security offload, and infrastructure acceleration.",
    note: "This is exactly why components need tags beyond a single category.",
  },
  {
    name: "Ubiquiti UniFi Dream Machine Pro",
    category: "Networking & Connectivity",
    componentType: "Network appliance",
    buyerFit: ["Retail", "Other"],
    role: "Small-site networking appliance for labs, offices, and light commercial deployments.",
    note: "Good SMB bundle component.",
  },
  {
    name: "MikroTik CCR2004",
    category: "Networking & Connectivity",
    componentType: "Router",
    buyerFit: ["Retail", "Other"],
    role: "Cost-effective router for advanced local networks and small edge deployments.",
    note: "Good value product for technical buyers.",
  },
  {
    name: "Cradlepoint E300",
    category: "Networking & Connectivity",
    componentType: "5G/LTE router",
    buyerFit: ["Retail", "Healthcare", "Transportation & Logistics"],
    role: "Cellular router for distributed sites and mobile edge systems.",
    note: "Already a live catalog candidate.",
  },
  {
    name: "Teltonika RUTX50",
    category: "Networking & Connectivity",
    componentType: "Industrial 5G router",
    buyerFit: ["Agriculture", "Transportation & Logistics"],
    role: "Industrial cellular router for remote field and vehicle deployments.",
    note: "Useful alternative to enterprise cellular routers.",
  },
  {
    name: "Starlink Standard Kit",
    category: "Networking & Connectivity",
    componentType: "Satellite terminal",
    buyerFit: ["Agriculture", "Transportation & Logistics", "Other"],
    role: "Satellite backhaul for remote AI deployments.",
    note: "Already a strong remote-ops product page candidate.",
  },
  {
    name: "Cisco Catalyst IE3400",
    category: "Networking & Connectivity",
    componentType: "Industrial Ethernet switch",
    buyerFit: ["Manufacturing", "Transportation & Logistics"],
    role: "Industrial switch for factory and field network infrastructure.",
    note: "Good enterprise-grade comparison product.",
  },
  {
    name: "Samsung 990 PRO 4TB NVMe",
    category: "Storage & Memory",
    componentType: "Consumer NVMe SSD",
    buyerFit: ["Other"],
    role: "Fast model and dataset storage for local AI workstations.",
    note: "Easy affiliate candidate for hobbyist and workstation guides.",
  },
  {
    name: "Crucial T700 PCIe 5.0 NVMe",
    category: "Storage & Memory",
    componentType: "PCIe 5.0 NVMe SSD",
    buyerFit: ["Other", "Manufacturing"],
    role: "High-speed local storage for model files, datasets, and scratch space.",
    note: "Verify thermals and heatsink requirements.",
  },
  {
    name: "Solidigm D7-P5520 U.2",
    category: "Storage & Memory",
    componentType: "Enterprise SSD",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "Enterprise NVMe storage for server-side local AI and RAG stores.",
    note: "Good for rackmount AI infrastructure content.",
  },
  {
    name: "Micron 7450 MAX NVMe",
    category: "Storage & Memory",
    componentType: "Enterprise SSD",
    buyerFit: ["Healthcare", "Manufacturing"],
    role: "Enterprise NVMe drive for write-heavy local datasets and document retrieval systems.",
    note: "Confirm endurance class for the workload.",
  },
  {
    name: "Kingston Server Premier DDR5 ECC RDIMM",
    category: "Storage & Memory",
    componentType: "Server memory",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "ECC memory for server and workstation local AI systems.",
    note: "Compatibility must be checked against motherboard QVLs.",
  },
  {
    name: "Mean Well HDR-60-24",
    category: "Power & Enclosures",
    componentType: "DIN rail power supply",
    buyerFit: ["Manufacturing", "Agriculture"],
    role: "Compact industrial 24V power supply for sensors and edge nodes.",
    note: "Small component that appears in many practical BOMs.",
  },
  {
    name: "Mean Well RSP-500-24",
    category: "Power & Enclosures",
    componentType: "Industrial power supply",
    buyerFit: ["Manufacturing"],
    role: "Higher-power 24V supply for cabinets, cameras, and industrial accessories.",
    note: "Confirm load, derating, and enclosure thermals.",
  },
  {
    name: "Corsair HX1500i",
    category: "Power & Enclosures",
    componentType: "ATX power supply",
    buyerFit: ["Other"],
    role: "High-wattage PSU for local AI GPU workstations.",
    note: "Useful for multi-GPU or high-power desktop builds.",
  },
  {
    name: "Noctua NF-A12x25",
    category: "Power & Enclosures",
    componentType: "Cooling fan",
    buyerFit: ["Other", "Manufacturing"],
    role: "High-quality fan for workstation, enclosure, and cooling upgrades.",
    note: "Small but practical affiliate component.",
  },
  {
    name: "Pelican 1450 Case",
    category: "Power & Enclosures",
    componentType: "Protective case",
    buyerFit: ["Agriculture", "Transportation & Logistics"],
    role: "Protective case for mobile edge kits, field sensors, and rugged transport.",
    note: "Good add-on for field deployment bundles.",
  },
  {
    name: "Universal Robots UR5e",
    category: "Robotics",
    componentType: "Collaborative robot arm",
    buyerFit: ["Manufacturing"],
    role: "Cobot arm for machine tending, inspection, and light automation.",
    note: "High-ticket comparison product with strong buyer intent.",
  },
  {
    name: "Universal Robots UR10e",
    category: "Robotics",
    componentType: "Collaborative robot arm",
    buyerFit: ["Manufacturing"],
    role: "Larger cobot arm for higher payload automation and production tasks.",
    note: "Compare payload, reach, and tooling ecosystem.",
  },
  {
    name: "Unitree Go2 EDU",
    category: "Robotics",
    componentType: "Quadruped robot",
    buyerFit: ["Other", "Manufacturing"],
    role: "Research and education quadruped for robotics learning and patrol concepts.",
    note: "Good robotics traffic product, but buyer intent may skew hobbyist/research.",
  },
  {
    name: "Unitree B2",
    category: "Robotics",
    componentType: "Industrial quadruped robot",
    buyerFit: ["Manufacturing", "Transportation & Logistics"],
    role: "Heavier quadruped for industrial inspection, patrol, and field robotics.",
    note: "High-interest robotics comparison candidate.",
  },
  {
    name: "MiR250",
    category: "Robotics",
    componentType: "Autonomous mobile robot",
    buyerFit: ["Manufacturing", "Transportation & Logistics"],
    role: "AMR for internal logistics, material movement, and warehouse workflows.",
    note: "Good fit for operations buyers comparing full robots.",
  },
  {
    name: "Clearpath Jackal UGV",
    category: "Robotics",
    componentType: "Unmanned ground vehicle",
    buyerFit: ["Agriculture", "Other"],
    role: "Research UGV for autonomy, outdoor robotics, and sensor payloads.",
    note: "Useful for bridging robotics and field edge AI.",
  },
  {
    name: "Elephant Robotics myCobot 320",
    category: "Robotics",
    componentType: "Desktop robot arm",
    buyerFit: ["Other", "Manufacturing"],
    role: "Lower-cost robot arm for education, prototyping, and light automation experiments.",
    note: "Good entry-level robotics catalog product.",
  },
  {
    name: "DJI Mavic 3M",
    category: "Drones",
    componentType: "Multispectral drone",
    buyerFit: ["Agriculture"],
    role: "Crop monitoring and field intelligence drone for precision agriculture.",
    note: "Already aligned with the agriculture catalog.",
  },
  {
    name: "DJI Matrice 350 RTK",
    category: "Drones",
    componentType: "Enterprise drone",
    buyerFit: ["Agriculture", "Transportation & Logistics", "Manufacturing"],
    role: "Enterprise drone platform for inspection, mapping, and multi-sensor payloads.",
    note: "Strong comparison anchor for professional drone buyers.",
  },
  {
    name: "DJI Agras T50",
    category: "Drones",
    componentType: "Agricultural spraying drone",
    buyerFit: ["Agriculture"],
    role: "Field execution drone for spraying and spreading operations.",
    note: "High-ticket agriculture product path.",
  },
  {
    name: "Autel EVO Max 4T",
    category: "Drones",
    componentType: "Enterprise drone",
    buyerFit: ["Transportation & Logistics", "Manufacturing"],
    role: "Enterprise drone for inspection, thermal imaging, and situational awareness.",
    note: "Useful alternative in DJI-heavy comparisons.",
  },
  {
    name: "Skydio X10",
    category: "Drones",
    componentType: "Autonomous inspection drone",
    buyerFit: ["Manufacturing", "Transportation & Logistics"],
    role: "Autonomous drone for inspection, public safety, and infrastructure monitoring.",
    note: "Strong autonomous robotics/inspection crossover.",
  },
  {
    name: "Meta Llama 3.3 / Llama 4 family",
    category: "AI Models",
    componentType: "Open-weight LLM",
    buyerFit: ["Other", "Manufacturing", "Retail"],
    role: "General-purpose open-weight model family for local and private AI deployments.",
    note: "Keep versions current because model naming changes quickly.",
  },
  {
    name: "Qwen3",
    category: "AI Models",
    componentType: "Open-weight LLM",
    buyerFit: ["Other", "Manufacturing"],
    role: "Strong open model family for coding, multilingual work, and local inference tests.",
    note: "Verify best checkpoints and licenses before recommending commercially.",
  },
  {
    name: "DeepSeek-R1",
    category: "AI Models",
    componentType: "Reasoning model",
    buyerFit: ["Other", "Manufacturing"],
    role: "Reasoning-focused model for local evaluation, agents, and technical workflows.",
    note: "Hardware requirements depend heavily on distilled vs full-size variants.",
  },
  {
    name: "Google Gemma 3",
    category: "AI Models",
    componentType: "Open model",
    buyerFit: ["Other", "Retail"],
    role: "Open model family for efficient local chat, experimentation, and app embedding.",
    note: "Good fit for beginner local AI content.",
  },
  {
    name: "Mistral Small 3.1",
    category: "AI Models",
    componentType: "Open/commercial model",
    buyerFit: ["Other", "Retail"],
    role: "Efficient model option for local assistants and commercial model comparisons.",
    note: "Check license and deployment terms by model release.",
  },
  {
    name: "Microsoft Phi-4",
    category: "AI Models",
    componentType: "Small language model",
    buyerFit: ["Other", "Healthcare"],
    role: "Compact model family for smaller local systems and edge inference experiments.",
    note: "Strong candidate for lower-resource hardware guides.",
  },
  {
    name: "Ollama",
    category: "Software & Runtimes",
    componentType: "Local model runner",
    buyerFit: ["Other", "Retail"],
    role: "Beginner-friendly local AI runtime for running and managing models.",
    note: "Default software recommendation for simple local AI setups.",
  },
  {
    name: "LM Studio",
    category: "Software & Runtimes",
    componentType: "Desktop local AI app",
    buyerFit: ["Other"],
    role: "GUI-first local AI app for model discovery, chat, and quick experiments.",
    note: "Good for non-technical buyers and LinkedIn-friendly guides.",
  },
  {
    name: "Open WebUI",
    category: "Software & Runtimes",
    componentType: "Chat interface",
    buyerFit: ["Other", "Retail"],
    role: "Self-hosted chat interface for local AI systems and small teams.",
    note: "Good bridge between local AI box and business usability.",
  },
  {
    name: "llama.cpp",
    category: "Software & Runtimes",
    componentType: "Inference engine",
    buyerFit: ["Other"],
    role: "Portable inference engine for CPUs, GPUs, Apple Silicon, and edge devices.",
    note: "Important for explaining GGUF and hardware flexibility.",
  },
  {
    name: "vLLM",
    category: "Software & Runtimes",
    componentType: "Serving runtime",
    buyerFit: ["Manufacturing", "Healthcare", "Retail"],
    role: "Higher-concurrency model serving layer for teams and private AI infrastructure.",
    note: "Best introduced after readers understand basic local AI.",
  },
  {
    name: "TensorRT-LLM",
    category: "Software & Runtimes",
    componentType: "NVIDIA inference runtime",
    buyerFit: ["Manufacturing", "Healthcare"],
    role: "NVIDIA-optimized runtime for maximum inference performance.",
    note: "Powerful but advanced; should be positioned as enterprise/serious builder software.",
  },
  {
    name: "Local AI Hobbyist Workstation Kit",
    category: "Solution Kits",
    componentType: "Starter bundle",
    buyerFit: ["Other"],
    role: "GPU, storage, memory, and software bundle for first local AI setup.",
    note: "Natural affiliate bundle built from articles already on the site.",
  },
  {
    name: "Manufacturing Visual Inspection Starter Kit",
    category: "Solution Kits",
    componentType: "Industrial bundle",
    buyerFit: ["Manufacturing"],
    role: "Camera, lighting, edge computer, model runtime, and mounting bundle for inspection.",
    note: "High-value path toward consulting-free monetization.",
  },
  {
    name: "Retail Real-Time Inventory Kit",
    category: "Solution Kits",
    componentType: "Commercial bundle",
    buyerFit: ["Retail"],
    role: "Depth camera, edge computer, local model, and dashboard bundle for shelf monitoring.",
    note: "Good bridge between product catalog and case-study traffic.",
  },
];
