export type PhysicalAiEvent = {
  name: string;
  shortName: string;
  startDate: string;
  endDate: string;
  dateLabel: string;
  month: string;
  monthKey: string;
  city: string;
  country: string;
  venue?: string;
  url: string;
  focus: string;
  summary: string;
  tier: "Anchor" | "Industry signal";
  workshops?: PhysicalAiWorkshop[];
};

export type PhysicalAiWorkshop = {
  name: string;
  schedule: string;
  focus: string;
  url: string;
};

export const physicalAiEvents: PhysicalAiEvent[] = [
  {
    name: "Global Open Source Innovation Meetup",
    shortName: "GOSIM Shenzhen",
    startDate: "2026-10-16",
    endDate: "2026-10-17",
    dateLabel: "October 16 to 17",
    month: "October 2026",
    monthKey: "october-2026",
    city: "Shenzhen",
    country: "China",
    venue: "ADEN Hotel Shenzhen Nanshan",
    url: "https://shenzhen2026.gosim.org/",
    focus: "Open source robotics",
    summary:
      "Embodied AI, humanoids, world models, simulation, robot learning, and autonomous navigation meet open source development.",
    tier: "Anchor",
    workshops: [
      {
        name: "AI Education Workshop",
        schedule: "Official schedule",
        focus: "AI education",
        url: "https://shenzhen2026.gosim.org/schedule/",
      },
      {
        name: "DORA Workshop",
        schedule: "Official schedule",
        focus: "Embodied robotics",
        url: "https://shenzhen2026.gosim.org/schedule/",
      },
      {
        name: "vLLM Workshop",
        schedule: "Official schedule",
        focus: "Model inference",
        url: "https://shenzhen2026.gosim.org/schedule/",
      },
      {
        name: "Google Cloud Workshop",
        schedule: "Official schedule",
        focus: "Agent development",
        url: "https://shenzhen2026.gosim.org/schedule/",
      },
      {
        name: "KVCDN Workshop",
        schedule: "Official schedule",
        focus: "AI infrastructure",
        url: "https://shenzhen2026.gosim.org/schedule/",
      },
    ],
  },
  {
    name: "RoboBusiness",
    shortName: "RoboBusiness",
    startDate: "2026-10-20",
    endDate: "2026-10-21",
    dateLabel: "October 20 to 21",
    month: "October 2026",
    monthKey: "october-2026",
    city: "Santa Clara",
    country: "United States",
    venue: "Santa Clara Convention Center",
    url: "https://www.robobusiness.com/",
    focus: "Commercial robotics",
    summary:
      "A concentrated view of robotics commercialization, product engineering, startup formation, deployment, and investment.",
    tier: "Anchor",
  },
  {
    name: "NVIDIA GTC Berlin",
    shortName: "NVIDIA GTC Berlin 2026",
    startDate: "2026-10-20",
    endDate: "2026-10-22",
    dateLabel: "October 20 to 22",
    month: "October 2026",
    monthKey: "october-2026",
    city: "Berlin",
    country: "Germany",
    venue: "STATION-Berlin and Tempodrom",
    url: "https://www.nvidia.com/en-eu/gtc/",
    focus: "Physical AI and infrastructure",
    summary:
      "NVIDIA's European developer conference covers the AI stack, including physical AI, robotics, simulation, AI infrastructure, and hands on technical training.",
    tier: "Anchor",
  },
  {
    name: "RobotWorld",
    shortName: "RobotWorld 2026",
    startDate: "2026-11-04",
    endDate: "2026-11-07",
    dateLabel: "November 4 to 7",
    month: "November 2026",
    monthKey: "november-2026",
    city: "Goyang",
    country: "South Korea",
    venue: "KINTEX",
    url: "https://eng.robotworld.or.kr/",
    focus: "Robotics exhibition",
    summary:
      "A major industry exhibition spanning industrial robots, service robots, logistics systems, drones, components, and software.",
    tier: "Industry signal",
  },
  {
    name: "Europe China Humanoid Robot and Physical AI Summit",
    shortName: "Humanoid Europe",
    startDate: "2026-11-05",
    endDate: "2026-11-06",
    dateLabel: "November 5 to 6",
    month: "November 2026",
    monthKey: "november-2026",
    city: "Munich",
    country: "Germany",
    url: "https://humanoidevent.com/",
    focus: "Humanoids",
    summary:
      "A focused industry program on embodied intelligence, dexterous manipulation, safety, supply chains, and humanoid production.",
    tier: "Anchor",
  },
  {
    name: "Conference on Robot Learning",
    shortName: "CoRL 2026",
    startDate: "2026-11-09",
    endDate: "2026-11-12",
    dateLabel: "November 9 to 12",
    month: "November 2026",
    monthKey: "november-2026",
    city: "Austin",
    country: "United States",
    url: "https://www.corl.org/",
    focus: "Robot learning",
    summary:
      "A leading research conference at the intersection of robotics and machine learning, including policies, foundation models, and sim to real systems.",
    tier: "Anchor",
    workshops: [
      {
        name: "Physics Simulation and World Models for Robotic Manipulation",
        schedule: "November 12 · Half day",
        focus: "World models",
        url: "https://corl26ws-physwm.github.io/",
      },
      {
        name: "Modeling Uncertainty in Robotic World Models",
        schedule: "November 12 · Half day",
        focus: "World models",
        url: "https://uncertainwm2026.github.io/",
      },
      {
        name: "Do Robots Need World Models?",
        schedule: "November 12 · Half day",
        focus: "Robot learning",
        url: "https://do-robots-need-world-models.github.io/",
      },
      {
        name: "Sim to Real to Field",
        schedule: "November 12 · Half day",
        focus: "Transfer learning",
        url: "https://sim2real2field-corl26.github.io/",
      },
      {
        name: "Efficient Foundation Models for Real Time Embodied AI",
        schedule: "November 12 · Half day",
        focus: "Embodied AI",
        url: "https://efficient-embodied-ai.github.io/",
      },
      {
        name: "Learn at Deploy: Robot Learning at Deployment",
        schedule: "November 12 · Half day",
        focus: "Deployment",
        url: "https://learn-at-deploy.github.io/",
      },
      {
        name: "Scaling Laws and Diversity in Human to Robot Learning",
        schedule: "November 12 · Half day",
        focus: "Human demonstrations",
        url: "https://scaling-h2r-corl.github.io/",
      },
      {
        name: "Dexterous Manipulation: Full Stack Robotics on Learning and Design",
        schedule: "November 12 · Half day",
        focus: "Dexterous manipulation",
        url: "https://dex-manipulation.github.io/",
      },
    ],
  },
  {
    name: "Physical AI Summit",
    shortName: "Physical AI Summit",
    startDate: "2026-11-12",
    endDate: "2026-11-12",
    dateLabel: "November 12",
    month: "November 2026",
    monthKey: "november-2026",
    city: "Providence",
    country: "United States",
    venue: "Brown University",
    url: "https://sair.foundation/event/physical-ai-summit-2026/",
    focus: "Embodied intelligence",
    summary:
      "Researchers, builders, industry leaders, and investors examine how embodied intelligence becomes reliable systems and companies.",
    tier: "Anchor",
  },
  {
    name: "Advanced Robotics Conference",
    shortName: "ARC 2026",
    startDate: "2026-11-25",
    endDate: "2026-11-26",
    dateLabel: "November 25 to 26",
    month: "November 2026",
    monthKey: "november-2026",
    city: "Aachen",
    country: "Germany",
    venue: "FEV",
    url: "https://www.fev.com/en/arc-2026/",
    focus: "Advanced robotics",
    summary:
      "Humanoids, intelligent robots, physical AI, sensors, actuators, and autonomous systems with a strong industrial lens.",
    tier: "Anchor",
  },
  {
    name: "ROS-Industrial Conference",
    shortName: "ROS-Industrial",
    startDate: "2026-12-03",
    endDate: "2026-12-04",
    dateLabel: "December 3 to 4",
    month: "December 2026",
    monthKey: "december-2026",
    city: "Stuttgart",
    country: "Germany",
    venue: "Fraunhofer IPA",
    url: "https://www.ipa.fraunhofer.de/en/Events/2026/ros-industrial-conference.html",
    focus: "Industrial deployment",
    summary:
      "Practical case studies and engineering lessons on applying ROS, AI, and open robotics software on the factory floor.",
    tier: "Industry signal",
  },
  {
    name: "NVIDIA GTC Washington, D.C.",
    shortName: "NVIDIA GTC Washington 2026",
    startDate: "2026-11-30",
    endDate: "2026-12-03",
    dateLabel: "November 30 to December 3",
    month: "November 2026",
    monthKey: "november-2026",
    city: "Washington, D.C.",
    country: "United States",
    venue: "Ronald Reagan Building and International Trade Center",
    url: "https://www.nvidia.com/gtc/dc/",
    focus: "Physical AI and policy",
    summary:
      "Physical AI, robotics, AI factories, and scientific computing meet government, policy, research, and industry audiences.",
    tier: "Anchor",
  },
  {
    name: "Consumer Electronics Show",
    shortName: "CES 2027",
    startDate: "2027-01-06",
    endDate: "2027-01-09",
    dateLabel: "January 6 to 9",
    month: "January 2027",
    monthKey: "january-2027",
    city: "Las Vegas",
    country: "United States",
    url: "https://www.ces.tech/about-ces/about-ces/",
    focus: "Product launches",
    summary:
      "A broad but globally influential launch stage for robotics, drones, autonomous mobility, sensors, edge AI, and intelligent machines.",
    tier: "Industry signal",
  },
  {
    name: "Robot Development and Application Expo",
    shortName: "RoboDEX Tokyo",
    startDate: "2027-02-17",
    endDate: "2027-02-19",
    dateLabel: "February 17 to 19",
    month: "February 2027",
    monthKey: "february-2027",
    city: "Tokyo",
    country: "Japan",
    venue: "Tokyo Big Sight",
    url: "https://www.fiweek.jp/tokyo/ja-jp/about/robo.html",
    focus: "Physical AI systems",
    summary:
      "Dedicated physical AI and humanoid areas alongside industrial robots, service robots, AGVs, components, and development tools.",
    tier: "Anchor",
  },
  {
    name: "Smart Factory and Automation World",
    shortName: "AW 2027",
    startDate: "2027-03-03",
    endDate: "2027-03-05",
    dateLabel: "March 3 to 5",
    month: "March 2027",
    monthKey: "march-2027",
    city: "Seoul",
    country: "South Korea",
    venue: "COEX",
    url: "https://www.automationworld.co.kr/",
    focus: "AI factories",
    summary:
      "Physical AI, collaborative robots, machine vision, AMRs, picking robots, logistics systems, and autonomous production.",
    tier: "Industry signal",
  },
  {
    name: "automatica Shanghai",
    shortName: "automatica Shanghai",
    startDate: "2027-03-08",
    endDate: "2027-03-10",
    dateLabel: "March 8 to 10",
    month: "March 2027",
    monthKey: "march-2027",
    city: "Shanghai",
    country: "China",
    venue: "Shanghai New International Expo Centre",
    url: "https://www.automatica-sh.com.cn/en/",
    focus: "Smart automation",
    summary:
      "The first Shanghai edition of the major robotics brand, covering industrial, collaborative, mobile, and service robots with AI driven automation.",
    tier: "Anchor",
  },
  {
    name: "NVIDIA GPU Technology Conference",
    shortName: "NVIDIA GTC 2027",
    startDate: "2027-03-14",
    endDate: "2027-03-18",
    dateLabel: "March 14 to 18",
    month: "March 2027",
    monthKey: "march-2027",
    city: "San Jose",
    country: "United States",
    venue: "San Jose McEnery Convention Center",
    url: "https://www.nvidia.com/gtc/",
    focus: "Physical AI and robotics",
    summary:
      "NVIDIA's flagship developer conference spans physical AI, robotics, simulation, AI infrastructure, research, and accelerated computing.",
    tier: "Anchor",
  },
  {
    name: "HANNOVER MESSE",
    shortName: "HANNOVER MESSE",
    startDate: "2027-04-05",
    endDate: "2027-04-08",
    dateLabel: "April 5 to 8",
    month: "April 2027",
    monthKey: "april-2027",
    city: "Hannover",
    country: "Germany",
    url: "https://www.hannovermesse.de/en/topics/automation-systems-components/",
    focus: "Industrial AI",
    summary:
      "A globally influential industrial platform where robotics, AI, automation, sensors, edge computing, and production systems converge.",
    tier: "Industry signal",
  },
  {
    name: "ProMat",
    shortName: "ProMat 2027",
    startDate: "2027-04-19",
    endDate: "2027-04-21",
    dateLabel: "April 19 to 21",
    month: "April 2027",
    monthKey: "april-2027",
    city: "Chicago",
    country: "United States",
    venue: "McCormick Place",
    url: "https://www.promatshow.com/about",
    focus: "Logistics robotics",
    summary:
      "A major commercial signal for warehouse robots, humanoids, picking systems, autonomous material handling, and supply chain automation.",
    tier: "Industry signal",
  },
  {
    name: "Automate",
    shortName: "Automate 2027",
    startDate: "2027-05-10",
    endDate: "2027-05-13",
    dateLabel: "May 10 to 13",
    month: "May 2027",
    monthKey: "may-2027",
    city: "Las Vegas",
    country: "United States",
    venue: "Las Vegas Convention Center",
    url: "https://www.automateshow.com/",
    focus: "Robotics and automation",
    summary:
      "North America's largest robotics and automation exhibition, with live systems, product launches, vision, motion, AI, and deployment expertise.",
    tier: "Anchor",
  },
  {
    name: "XPONENTIAL",
    shortName: "XPONENTIAL 2027",
    startDate: "2027-05-17",
    endDate: "2027-05-20",
    dateLabel: "May 17 to 20",
    month: "May 2027",
    monthKey: "may-2027",
    city: "Miami",
    country: "United States",
    url: "https://xponential.org/",
    focus: "Autonomous systems",
    summary:
      "A major autonomy gathering covering aerial, ground, maritime, and uncrewed robotic systems across commercial and public applications.",
    tier: "Industry signal",
  },
  {
    name: "IEEE International Conference on Robotics and Automation",
    shortName: "ICRA 2027",
    startDate: "2027-05-24",
    endDate: "2027-05-28",
    dateLabel: "May 24 to 28",
    month: "May 2027",
    monthKey: "may-2027",
    city: "Seoul",
    country: "South Korea",
    venue: "COEX",
    url: "https://2027.ieee-icra.org/about/",
    focus: "Robotics research",
    summary:
      "The flagship IEEE robotics conference, bringing together leading research, industry exhibitions, competitions, workshops, and technical forums.",
    tier: "Anchor",
  },
  {
    name: "Robotics Summit and Expo",
    shortName: "Robotics Summit",
    startDate: "2027-06-02",
    endDate: "2027-06-03",
    dateLabel: "June 2 to 3",
    month: "June 2027",
    monthKey: "june-2027",
    city: "Boston",
    country: "United States",
    venue: "John B. Hynes Convention Center",
    url: "https://www.roboticssummit.com/",
    focus: "Robotics engineering",
    summary:
      "A highly practical event for engineers and leaders building, deploying, financing, and scaling commercial robotics systems.",
    tier: "Anchor",
  },
  {
    name: "automatica Munich",
    shortName: "automatica 2027",
    startDate: "2027-06-22",
    endDate: "2027-06-25",
    dateLabel: "June 22 to 25",
    month: "June 2027",
    monthKey: "june-2027",
    city: "Munich",
    country: "Germany",
    venue: "Messe München",
    url: "https://automatica-munich.com/en/trade-fair/",
    focus: "Physical AI industry",
    summary:
      "One of the world's most important commercial robotics shows, with physical AI, smart automation, machine vision, and the future of work at its core.",
    tier: "Anchor",
  },
];
