import type { CaseStudyArticle } from "@/lib/case-studies";

const atlasCaption =
  "Original Black Scarab illustration. Representative engineering architecture. Internal layouts vary by manufacturer and this is not a proprietary robot teardown.";

export const humanoidAnatomyDeepDive = (): CaseStudyArticle => ({
  slug: "humanoid-robot-anatomy-components-suppliers-guide",
  title: "Humanoid Robot Anatomy: The Complete Component and Supplier Guide",
  summary:
    "A medical style dissection of the modern humanoid robot, from skeleton, joints, actuators, hands, batteries, and cable harnesses to vision, GPUs, tactile sensing, thermal management, safety, suppliers, failure modes, and service economics.",
  publishedLabel: "Deep Dive · Published September 7, 2026",
  publishedDate: "2026-09-07",
  typeLabel: "Deep Dive",
  formatLabel: "Component anatomy, supplier atlas, and engineering field guide",
  industry: "Humanoid Robotics",
  image: "/article-images/humanoid-anatomy/hero-exploded-humanoid.png",
  imageAlt:
    "Exploded anatomy of a humanoid robot showing its skeleton, joints, hands, battery, compute, sensors, wiring, and protective shell.",
  seoDescription:
    "Explore every major humanoid robot component, how the systems connect, which companies make them, what fails, and how leading platforms compare.",
  tags: [
    "humanoid robot components",
    "humanoid robot anatomy",
    "robot actuators",
    "robot batteries",
    "robot cable harnesses",
    "robot vision systems",
    "robot tactile sensors",
    "robot GPUs",
    "humanoid robot suppliers",
    "physical AI hardware",
  ],
  author: {
    name: "Rodolfo Garcia Calderoni, CFA",
    href: "/about",
  },
  sections: [
    {
      paragraphs: [
        "Open a humanoid robot and the machine stops looking like one product. It becomes a compact ecosystem of structural frames, precision transmissions, electric motors, bearings, battery cells, power converters, computers, cameras, encoders, touch sensors, cables, seals, cooling hardware, and safety controllers. Every piece competes for the same limited mass, volume, power, thermal capacity, and service access.",
        "The medical analogy is useful because a humanoid is organized like a body. The frame is its skeleton. Motors are muscles. Reducers and bearings form the joints. Tendons appear as cables, belts, and screws. Cameras are eyes. An inertial measurement unit behaves like an inner ear. Encoders and force sensors create proprioception. The cable harness is a nervous system. The battery and power bus provide metabolism and circulation. Cooling maintains homeostasis. Safety electronics provide reflexes that must remain dependable even when the main AI computer is confused.",
        "This atlas decomposes those systems to the component level, shows how signals and forces pass through the body, identifies the companies that build each layer, and separates public supplier relationships from commercially suitable products. That final distinction is essential. Most humanoid makers do not publish complete bills of materials, and a supplier that makes an appropriate component is not automatically inside Tesla Optimus, Figure 03, Apollo, Atlas, Digit, or any other named robot.",
      ],
      tables: [
        {
          title: "The Humanoid Body in One Page",
          columns: ["Biological System", "Robot Equivalent", "Primary Job", "Typical Failure"],
          rows: [
            ["Skeleton", "Torso, pelvis, links, housings, fasteners", "Carry loads and preserve joint geometry", "Fatigue, loosened interfaces, deformation, impact damage"],
            ["Muscles", "Motors and integrated actuators", "Convert electrical energy into motion", "Heat, winding damage, demagnetization, controller failure"],
            ["Joints", "Reducers, bearings, shafts, brakes", "Multiply torque and carry complex loads", "Backlash, wear, grease loss, bearing damage"],
            ["Tendons", "Cables, belts, linkages, ball screws", "Transmit force while controlling mass placement", "Stretch, fatigue, routing friction, loss of calibration"],
            ["Brain", "GPU, CPU, memory, storage", "Perception, planning, learned policy, coordination", "Thermal throttling, memory pressure, timing instability"],
            ["Spinal cord", "Real time controller, fieldbus, joint drives", "Fast deterministic balance and torque control", "Clock drift, packet loss, missed deadlines"],
            ["Eyes and inner ear", "Cameras, depth, lidar, IMU", "Scene geometry, motion, orientation, localization", "Glare, occlusion, contamination, vibration, drift"],
            ["Touch and proprioception", "Encoders, force torque sensors, tactile arrays", "Measure joint state, contact, slip, and load", "Calibration drift, elastomer wear, sensor disagreement"],
            ["Heart and metabolism", "Battery, BMS, converters, charging", "Store, protect, and distribute energy", "Cell imbalance, overheating, contactor or interconnect failure"],
            ["Nerves", "Harnesses, connectors, flexible circuits", "Move power and data through a moving body", "Copper fatigue, fretting, abrasion, electromagnetic noise"],
            ["Skin", "Covers, foam, textiles, seals, optical windows", "Protect people and internal components", "Tearing, contamination, seal drag, hidden damage"],
            ["Reflexes", "Safety PLC, E stops, brakes, STO, contactors", "Create an independent path to a safe state", "Unsafe common cause failure or nuisance stops"],
          ],
          note: "A commercial humanoid is a system of systems. No single specification predicts whether the complete body will survive productive work.",
        },
      ],
    },
    {
      heading: "How to Read the Supplier Atlas",
      paragraphs: [
        "The humanoid supply chain is unusually opaque. Robot companies often say that a subsystem is designed internally while still purchasing cells, semiconductors, image sensors, connectors, bearings, magnets, passive components, and manufacturing services. In house design describes architectural control. It does not mean every physical part is fabricated by the robot maker.",
        "Every company named in this guide belongs to one of four evidence classes. The labels prevent a common market research error: converting product suitability into an unsupported customer claim.",
      ],
      tables: [
        {
          title: "Evidence Classes Used Throughout This Guide",
          columns: ["Class", "Meaning", "What Can Be Said"],
          rows: [
            ["Confirmed integration", "The robot maker or component company identifies a specific component or supplier on a named platform.", "The relationship and configuration can be described with its source and date."],
            ["Confirmed partnership", "Both parties disclose development, supply, evaluation, or adoption, but the exact production configuration may remain private.", "The partnership can be stated, while installed content must remain qualified."],
            ["Commercial supplier", "The company offers a component explicitly designed or technically suitable for humanoid robotics.", "It belongs in the supplier landscape, not in a named robot bill of materials."],
            ["OEM design, vendor private", "The robot maker claims control of the design but does not identify underlying vendors.", "Describe the architecture as internal and keep merchant component suppliers undisclosed."],
          ],
        },
      ],
    },
    {
      heading: "1. The Skeleton: Structure, Load Paths, and Packaging",
      paragraphs: [
        "The frame carries body weight, payload, ground impact, joint reaction loads, and the violence of a fall. It also fixes the coordinate system that every encoder and control model assumes. If a shoulder carrier or leg link bends under load, the controller sees an error that no amount of software can fully erase.",
        "A strong frame is not necessarily a heavy frame. Added mass increases motor torque, battery drain, impact energy, and the strength required everywhere below it. Mass in a hand is costly to the wrist, elbow, and shoulder. Mass in the torso is costly to the hips, knees, ankles, and feet. Designers therefore use machined or cast aluminum around concentrated loads, steel for compact shafts and hardened interfaces, thin wall links or composites for limbs, and molded polymers or textiles for nonstructural covers.",
        "The most efficient structures perform several jobs. A joint housing can carry load, locate bearings, spread motor heat, seal grease, and route cables. A battery enclosure can reinforce the torso. A limb shell can guide airflow and keep fingers away from pinch points. This multifunctional packaging saves mass, but it can make repair harder when one damaged part performs too many unrelated functions.",
        "Figure says Figure 03 shifted from the predominantly machined construction of Figure 02 toward die casting, stamping, and injection molding. Its battery housing uses stamped steel, die cast aluminum, and structural adhesive as a load bearing torso member. Boston Dynamics emphasizes common Atlas actuator modules and simple links. 1X wraps a low inertia tendon driven body in a custom lattice polymer exterior. These are different answers to the same anatomy problem: stiffness, low mass, safe contact, manufacturability, and service access must coexist.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/skeleton-structure.png",
        alt: "Humanoid robot skeleton with torso frame, pelvis, limb links, bearings, shafts, and structural interfaces separated for inspection.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "Structural Regions and Material Logic",
          columns: ["Region", "Typical Construction", "Engineering Priority", "Supplier Landscape"],
          rows: [
            ["Torso and pelvis", "Cast or machined aluminum, stamped steel, hybrid composite", "Bending stiffness, battery integration, heat spreading", "Jabil and other manufacturing partners; BASF and Covestro material systems; OEM custom structures"],
            ["Joint carriers", "Machined or cast aluminum with steel inserts", "Bearing alignment, torque reaction, fatigue", "Precision casting and machining ecosystem; robot OEM design"],
            ["Arm and leg links", "Thin wall metal, carbon composite, hybrid structures", "Low distal inertia and impact resistance", "BASF and Covestro materials; specialist composite and metal fabricators"],
            ["Covers and padding", "Polycarbonate blends, TPU, foam, lattice polymer, textile", "Pinch protection, contact softness, access", "BASF, Covestro, 3M, Henkel, contract molding and soft goods firms"],
            ["Fasteners and bonds", "High strength bolts, inserts, thread lockers, structural adhesive", "Joint retention and repeatable service", "Bossard, Böllhoff, Henkel, 3M, and broad industrial supply base"],
          ],
          note: "BASF and Fourier have disclosed a material development relationship. Other companies in this table are category suppliers unless a direct platform relationship is separately stated.",
        },
      ],
    },
    {
      heading: "2. The Joint Is an Organ, Not a Motor",
      paragraphs: [
        "A rotary joint is the densest mechanical organ in the body. It may contain a frameless motor, inverter, rotor encoder, reduction mechanism, output bearing, output encoder, torque sensor, brake, controller, seals, grease, temperature sensing, cooling fins, structural interfaces, and a hollow path for cables. The quality of this integration often determines the robot's weight, control quality, noise, heat, durability, and repair time.",
        "The motor creates speed and torque. The reducer trades speed for higher output torque. The bearing carries radial load, axial load, and overturning moment. The encoders measure rotor and joint position. A torque sensor or calibrated compliant element estimates force. The drive electronics switch battery power through the motor phases. The housing aligns everything and becomes the main thermal path into the frame.",
        "Peak torque attracts attention, but continuous torque pays for work. A knee can briefly produce a spectacular number and still overheat during repetitive lifting. Continuous output depends on winding temperature, inverter losses, gearbox friction, housing conduction, airflow, duty cycle, ambient temperature, and how often adjacent joints generate heat at the same time.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/joint-actuator.png",
        alt: "Exploded humanoid joint actuator with motor, controller, gears, bearings, encoders, torque sensing, brake, hollow bore, and housing.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "Exploded Joint Anatomy",
          columns: ["Layer", "Function", "Design Question", "Representative Companies"],
          rows: [
            ["Frameless motor", "Creates electromagnetic torque", "How much continuous torque per kilogram and per liter?", "maxon, Kollmorgen, TQ RoboDrive, Moog, Schaeffler"],
            ["Servo drive", "Controls phase current and motor torque", "Can it close fast loops efficiently inside a hot joint?", "Synapticon, Elmo Motion Control, Copley, TI, Infineon, ST"],
            ["Reducer", "Converts motor speed into joint torque", "What balance of backlash, shock life, efficiency, and backdrivability is required?", "Harmonic Drive, Nabtesco, Leaderdrive, Schaeffler, Nidec"],
            ["Output bearing", "Carries combined body and payload loads", "Can one compact bearing handle radial, axial, and moment loading?", "Schaeffler, SKF, THK, NSK, NTN, Timken"],
            ["Dual encoders", "Measure rotor and actual output position", "Can the controller detect reducer compliance, wear, and disagreement?", "RLS, HEIDENHAIN, Renishaw, ams OSRAM, Celera Motion"],
            ["Torque sensing", "Measures joint load or flexure deflection", "Is direct sensing worth its mass, cost, and calibration burden?", "Bota Systems, ATI, Schaeffler, OEM internal designs"],
            ["Brake", "Holds selected axes when power is removed", "Which joints must resist collapse without motor current?", "mayr, Miki Pulley, Kendrion, OEM internal selection"],
            ["Housing and seals", "Aligns, protects, lubricates, and rejects heat", "Can the cartridge survive dust, impact, heat, and field replacement?", "Trelleborg, Parker, Freudenberg, OEM housings"],
          ],
        },
      ],
    },
    {
      heading: "3. Muscles: Motor and Actuator Families",
      paragraphs: [
        "Most humanoids use permanent magnet electric motors, but motor geometry and transmission choice create very different behavior. A high speed inner rotor motor paired with a large reduction can be compact and powerful. An outer rotor torque motor can deliver more torque at lower speed. A quasi direct drive uses a torque dense motor and a low reduction ratio to improve backdrivability. A linear actuator uses a screw and linkage to resemble a muscle pulling across a joint.",
        "Frameless motors remove the separate motor case and install the rotor and stator directly into the joint housing. That saves volume and mass, but the robot designer inherits responsibility for alignment, bearing selection, contamination, electromagnetic compatibility, and heat removal. Integrated actuator suppliers package more of that risk into a tested module.",
        "Public examples show the range of strategies. Unitree describes internal rotor permanent magnet joint motors with hollow routing and dual encoders. Apptronik describes proprietary linear and rotary force controlled actuators. 1X says it winds and manufactures its Revo2 motors internally for a tendon driven system. Boston Dynamics says Atlas standardizes much of its body around only two powerful actuator types. PAL describes custom linear actuators in Kangaroo. There is no universal humanoid muscle.",
      ],
      tables: [
        {
          title: "Actuation Architectures",
          columns: ["Architecture", "Strength", "Tradeoff", "Likely Body Region"],
          rows: [
            ["High ratio strain wave joint", "Compact, precise, low backlash, large reduction in one stage", "Flexspline fatigue, compliance, lower backdrivability", "Shoulder, elbow, wrist, waist"],
            ["Planetary joint", "Efficient, familiar, durable, scalable", "Backlash control and multiple stage complexity", "Hip, knee, shoulder, general joints"],
            ["Cycloidal or planocentric joint", "High stiffness, torque, and shock tolerance", "Geometry, mass, vibration, and precision manufacturing", "Highly loaded hips and knees"],
            ["Quasi direct drive", "Low reflected inertia, force transparency, natural contact", "Larger motor and higher current demand", "Arms, hands, ankles, dynamic legs"],
            ["Linear screw actuator", "High force density and muscle like packaging", "Screw cost, linkage geometry, side loading, service complexity", "Knees, hips, torso"],
            ["Tendon drive", "Moves motors away from fingers and distal limbs", "Stretch, friction, routing wear, calibration", "Hands, forearms, soft body architectures"],
          ],
        },
        {
          title: "Public Actuator Evidence",
          columns: ["Company or Platform", "Publicly Supported Claim", "Evidence Class"],
          rows: [
            ["Schaeffler and Humanoid", "Development and supply agreement for strain wave actuators, primarily for upper body joints", "Confirmed partnership"],
            ["maxon and Reachy 2", "Exact EC, ECX, MILE, ENX, and GPX components are documented in Orbita joints", "Confirmed integration"],
            ["Unitree H1", "Unitree branded M107 joint with hollow shaft, dual encoders, and crossed roller output bearing", "OEM design, underlying vendors private"],
            ["Apptronik Apollo", "Proprietary linear and rotary actuator architecture", "OEM design, underlying vendors private"],
            ["1X NEO", "In house Revo2 motor winding, actuator production, and tendon architecture", "OEM design, underlying vendors private"],
            ["Synapticon ACTILINK", "Integrated humanoid joint family with servo drive and planetary or shaft gearing", "Commercial supplier"],
            ["Harmonic Drive", "Integrated actuator and strain wave component families for compact robotics", "Commercial supplier"],
          ],
        },
      ],
    },
    {
      heading: "4. Reducers, Bearings, Brakes, and Proprioception",
      paragraphs: [
        "The reducer transforms the motor's useful operating speed into the torque required at the limb. Strain wave gearing uses a wave generator, flexible spline, and circular spline. Planetary gearing divides load among several planets. Cycloidal systems distribute contact across lobes or pins. Linear drives convert rotation into translation through ball screws or planetary roller screws.",
        "The bearing is the cartilage of the machine. A reducer can transmit torque, but the output bearing carries the robot. Crossed roller bearings are attractive because alternating rollers support radial, axial, and moment loads within one compact ring. Thin section bearings preserve hollow bores. Angular contact pairs control axial and radial loads. Needle bearings save radial space in linkages.",
        "Two encoders answer different questions. The motor encoder measures the rotor before the gearbox and supports commutation and fast velocity control. The output encoder measures the actual joint after backlash, compliance, flex, and wear. Comparing both creates better accuracy and a valuable health signal. RLS and HEIDENHAIN market dual encoder architectures that package both measurements around a hollow joint.",
        "A holding brake is usually spring applied and electrically released. When power disappears, selected gravity loaded joints can remain controlled instead of collapsing. Brakes add weight, drag, heat, cost, and another failure mode, so many designs use them selectively or rely on counterbalance, controlled descent, mechanical stops, and compliant collapse strategies.",
      ],
      tables: [
        {
          title: "Transmission and Bearing Supplier Map",
          columns: ["Component", "Representative Suppliers", "Public Robot Evidence"],
          rows: [
            ["Strain wave reducers", "Harmonic Drive, Schaeffler, Leaderdrive, Nabtesco", "Schaeffler has a public supply relationship with Humanoid. Other named platform relationships remain private in cited materials."],
            ["Planetary reducers", "maxon, Schaeffler, Neugart, Wittenstein, Nidec", "maxon GPX models are documented in Reachy 2."],
            ["Cycloidal reducers", "Nabtesco, Sumitomo Drive Technologies, Spinea", "Commercially suitable; current target platform relationships are generally undisclosed."],
            ["Ball and roller screws", "Schaeffler, THK, Bosch Rexroth, Ewellix, HIWIN", "Schaeffler publicly positions a complete linear motion portfolio for humanoids."],
            ["Crossed roller bearings", "THK, Schaeffler, SKF, NSK, IKO", "Unitree confirms the bearing type in M107 but not the supplier."],
            ["Encoders", "RLS, HEIDENHAIN, Renishaw, ams OSRAM, Celera Motion", "RLS documents integration on PAL REEM C; other current humanoid ties vary."],
            ["Holding brakes", "mayr, Miki Pulley, Kendrion", "Suitable compact robotic products; named current humanoid customers not publicly confirmed here."],
          ],
        },
      ],
    },
    {
      heading: "5. Hands: A Robot at the End of Each Arm",
      paragraphs: [
        "A dexterous hand is not an accessory. It is another dense robot containing palm structure, phalanges, tiny bearings, miniature motors, gear stages or screws, tendons, pulleys, springs, encoders, force sensing, tactile arrays, palm cameras, flexible circuits, local control, and protective skin. Every gram in the hand multiplies the effort required from the wrist, elbow, and shoulder.",
        "A fully actuated hand offers independent control but creates extraordinary wiring, thermal, and reliability demands. An underactuated hand lets several joints conform mechanically around an object with fewer motors. A tendon driven hand moves motors into the palm or forearm to reduce finger mass, while accepting tendon stretch, creep, routing friction, and recalibration. For repetitive logistics, a two or three finger gripper may outperform a beautiful humanlike hand.",
        "Touch closes the manipulation loop. Sparse pressure pads confirm contact. Three axis taxels estimate normal and shear force. Optical tactile sensors observe deformation of an elastomer to recover contact geometry, texture, and slip. More sensory channels can improve dexterity, but they also create more wiring, data, calibration, wear surfaces, and machine learning burden.",
        "Figure describes internal fingertip sensors that detect forces near three grams and palm cameras that see around occlusions. 1X describes a 25 degree of freedom hand with quasi direct tendon drives. Sanctuary AI integrates proprietary tactile sensing into Phoenix. NVIDIA's H2 reference design pairs a Unitree chassis with Sharpa Wave tactile hands. These are direct architectural disclosures. They do not establish that independent hand suppliers appear in other undisclosed robots.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/dexterous-hand.png",
        alt: "Humanoid robotic hands showing finger mechanisms, tendons, motors, tactile pads, palm camera, wrist sensing, and forearm electronics.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "Hand and Touch Companies",
          columns: ["Company", "What It Provides", "Evidence Class"],
          rows: [
            ["Shadow Robot", "Tendon driven Dexterous Hand and DEX EE with many sensors and tactile options", "Commercial supplier"],
            ["SCHUNK", "SVH five finger hand and a dedicated humanoid hand development company", "Commercial supplier and active humanoid development"],
            ["Tesollo", "DG 5F dexterous five finger hand", "Commercial supplier"],
            ["Wonik Robotics", "Allegro Hand research platform", "Commercial supplier"],
            ["qb robotics", "SoftHand underactuated compliant hand", "Commercial supplier"],
            ["Inspire Robots and Seed Robotics", "Hands offered as PAL Kangaroo options", "Confirmed platform options"],
            ["XELA Robotics", "uSkin three axis tactile arrays for fingertips, phalanges, palms, and grippers", "Commercial supplier with hand level integrations"],
            ["GelSight", "Optical elastomer tactile sensors for high resolution contact geometry", "Commercial supplier"],
            ["Figure and Sanctuary AI", "Internally developed fingertip and haptic sensing", "OEM design, underlying vendors private"],
          ],
          note: "Hand specifications change quickly. Compare active degrees of freedom, joint count, force, speed, sensor coverage, replacement cost, and demonstrated cycle life rather than one headline number.",
        },
      ],
    },
    {
      heading: "6. Feet and Balance: Where the Model Meets the Floor",
      paragraphs: [
        "A humanoid foot is simultaneously a load path, a sensor, an impact absorber, a friction surface, and sometimes a charging interface. The ankle must manage pitch and roll while the sole transmits ground reaction force into the body. The controller needs to know whether the heel, toe, or edge is touching, where the center of pressure sits, and whether the contact is beginning to slip.",
        "A typical foot may contain a structural metal plate, ankle actuators, joint encoders, a six axis force torque sensor, pressure or contact sensors, compliant heel and toe elements, wiring, sealed connectors, replaceable tread, and shock isolation. Some designs add an active toe. Figure 03 adds inductive charging coils in its feet, so the same organ that controls balance also receives two kilowatts of charging power.",
        "The sole is a consumable component with an outsized effect on control. Dust, oil, water, wear, temperature, and floor material change friction. A balance policy trained against a fresh sole on clean concrete can become unreliable when tread is polished or contaminated. Vibram's disclosed sole collaboration with Agility Robotics is a useful reminder that footwear science is part of humanoid engineering.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/foot-balance.png",
        alt: "Exploded humanoid ankle and foot showing actuators, bearings, force torque sensing, pressure sensors, compliant tread, toe, wiring, and charging coil.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "What the Foot Must Know",
          columns: ["Signal", "Hardware", "Control Use", "Failure Consequence"],
          rows: [
            ["Ground reaction force", "Ankle or foot force torque sensor", "Estimate body support and load transfer", "Poor balance, damaging steps, uncertain contact"],
            ["Center of pressure", "Force torque sensor or distributed pressure array", "Keep the projected mass inside the support region", "Edge loading and falls"],
            ["Contact state", "Pressure pads, switches, torque estimates", "Change walking phase and stabilize landing", "Early or late gait transition"],
            ["Slip", "Shear sensing, IMU, vision, kinematic mismatch", "Reduce tangential force and recover stance", "Unexpected foot motion and collapse"],
            ["Ankle angle and torque", "Dual encoders, current sensing, joint torque sensor", "Whole body state estimation", "Accumulating pose error"],
            ["Sole condition", "Inspection, force signature, maintenance record", "Adjust friction model and schedule replacement", "Gradual reliability loss that software may misdiagnose"],
          ],
        },
      ],
    },
    {
      heading: "7. Energy Metabolism: Cells, Pack, BMS, and Charging",
      paragraphs: [
        "The battery has to support two different loads at once. Compute, sensors, and communications create a persistent background draw. Walking, catching balance, lifting, and recovering from contact create fast current peaks. Decelerating joints can return regenerative energy to the bus. Pack design must therefore consider peak current, voltage sag, regeneration acceptance, heat, and fault containment, not just average energy consumption.",
        "A complete pack begins with cells connected in series for voltage and in parallel for capacity and current. Cell holders, busbars or fusible wire bonds, thermistors, and compression structures form modules. A battery management system measures cell voltage and temperature, estimates state of charge and health, balances cells, and commands protection. The high power path adds a service disconnect, primary fuse, precharge circuit, contactors, current sensing, and a distribution bus. Converters create lower voltage rails for compute, sensors, fans, safety, and logic.",
        "Figure's F.03 battery is the clearest public pack anatomy from a leading humanoid maker. Figure describes a 2.3 kWh structural torso pack, custom BMS, active cooling, potting, thermal propagation protection, a flame arresting vent, and cell wire bonds tuned as fusible links. It claims five hours of peak performance and two kilowatt charging. The underlying cell maker remains private.",
        "Unitree lists a 13 series, 9,000 mAh smart quick release battery for G1 and an 864 Wh pack for H1. PAL lists a 1,080 Wh TALOS pack with up to 100 A discharge. 1X lists an 842 Wh NEO pack. These numbers are not directly comparable without voltage, task, duty cycle, payload, software, and thermal context. Amp hours alone are especially misleading across different pack voltages. Use watt hours for energy and study the current profile separately.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/battery-power.png",
        alt: "Humanoid torso battery system with cylindrical cells, structural pack, BMS, contactors, fuses, busbars, converters, cooling, and charging hardware.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "Battery Autopsy",
          columns: ["Layer", "What It Does", "What Must Be Verified"],
          rows: [
            ["Cell chemistry and format", "Stores electrochemical energy", "Energy density, power, cycle life, temperature, propagation behavior, availability"],
            ["Series and parallel topology", "Sets voltage, capacity, and current sharing", "Worst cell behavior, balancing, busbar resistance, pack voltage window"],
            ["BMS", "Monitors and protects cells", "Measurement accuracy, open wire detection, fault coverage, state estimation, communications"],
            ["Fuse and disconnect", "Interrupts severe faults and permits service isolation", "Fault current rating, access, arc control, replacement process"],
            ["Precharge and contactors", "Connects the pack without destructive inrush", "Weld detection, redundant isolation, coil power, safe failure"],
            ["Current sensor", "Measures load and regenerative flow", "Bandwidth, offset drift, isolation, bidirectional range"],
            ["Thermal system", "Moves cell heat and limits propagation", "Cooling under peak load, vent path, sensor coverage, blocked airflow"],
            ["Structural enclosure", "Contains cells and may carry torso load", "Impact, puncture, fall, ingress, service and transport tests"],
            ["Charge system", "Restores energy by cable, dock, or inductive interface", "Power, cooling, alignment, unattended operation, fleet scheduling"],
          ],
        },
        {
          title: "Battery and Power Company Map",
          columns: ["Company", "Capability", "Evidence Class"],
          rows: [
            ["CATL", "Cells and battery systems; CATL identifies Galbot S1 as battery powered by CATL", "Confirmed named platform"],
            ["LG Energy Solution", "Cylindrical and pouch cells, modules, and packs marketed for robots", "Commercial supplier; named humanoid customers private"],
            ["Samsung SDI", "Robot battery development with Hyundai and Kia Robotics Lab", "Confirmed development partnership"],
            ["Molicel", "High power cylindrical cells including P45B and P50B", "Commercial supplier; Molicel says P50B entered humanoid applications"],
            ["Figure", "Pack, BMS, enclosure, cooling, and manufacturing designed internally", "OEM design; cell vendor private"],
            ["TI, Analog Devices, NXP, Infineon", "Cell monitoring, protection, balancing, current sensing, and power control silicon", "Commercial supplier candidates"],
            ["Sensata and TE", "High current contactors and switching", "Commercial supplier candidates"],
            ["Littelfuse and Eaton", "Fusing and circuit protection", "Commercial supplier candidates"],
            ["Vicor, Murata, TDK Lambda", "High density DC conversion", "Commercial supplier candidates"],
          ],
          note: "A suitable BMS chip, cell, or contactor does not prove use in a named robot. The exact pack supply chain is private for most humanoids.",
        },
      ],
    },
    {
      heading: "8. The Brain Is a Hierarchy, Not One GPU",
      paragraphs: [
        "A humanoid needs several layers of computation with different timing contracts. The main AI computer processes cameras, language, mapping, foundation models, and learned policies. A real time controller converts intentions into coordinated body targets. Distributed joint controllers close position, velocity, and torque loops. Motor control units switch phase current at far higher frequency. An independent safety controller monitors limits and can command a safe state.",
        "The lower a control layer sits, the faster and more deterministic it must become. A semantic model may run around tens of updates per second. Figure says Helix 02 produces full body joint targets at 200 Hz, while its whole body controller runs at 1 kHz. PAL describes EtherCAT control at 2 kHz and as high as 5 kHz on TALOS. Motor current loops commonly operate in the tens of kilohertz. These examples illustrate a principle, not a universal timing specification.",
        "The GPU should not directly switch every motor, and the AI computer should not be the only device capable of stopping the robot. Variable inference latency, model updates, operating system load, and thermal throttling are incompatible with the strictest reflex loops. Intelligence can propose motion. Deterministic controllers and safety hardware must enforce physical limits.",
        "NVIDIA Jetson Thor currently defines the high end merchant compute category. NVIDIA lists as much as 2,070 sparse FP4 TFLOPS, 128 GB of memory, 273 GB per second of bandwidth, and configurable power from 40 to 130 W. NVIDIA has publicly connected Thor with Boston Dynamics, Agility, Figure, 1X, and its Unitree H2 based reference design at different stages of adoption. Qualcomm, AMD, Intel, and custom OEM silicon create other paths. TOPS and TFLOPS remain poor comparisons unless precision, sparsity, memory bandwidth, model shape, power, and latency are held constant.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/compute-control.png",
        alt: "Humanoid compute hierarchy with edge AI module, GPU board, real time controller, network switch, safety electronics, and distributed joint control boards.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "Control Rate Pyramid",
          columns: ["Layer", "Illustrative Rate", "Work", "Failure Tolerance"],
          rows: [
            ["Semantic perception and VLA reasoning", "Roughly 10 to 30 Hz", "Interpret scenes, language, objects, and task context", "Can tolerate some variable latency but not stale world state"],
            ["Motion policy", "Roughly 100 to 200 Hz", "Generate whole body or limb targets", "Timing variation degrades smoothness and response"],
            ["Whole body control", "Roughly 500 to 1,000 Hz or higher", "Balance, contact, constraints, coordinated torque", "Missed deadlines can destabilize the robot"],
            ["Joint servo", "Kilohertz class", "Position, velocity, torque, and impedance loops", "Requires deterministic local execution"],
            ["Motor current control", "Tens of kilohertz", "Field oriented control and phase current regulation", "A missed deadline can create poor torque or a hardware fault"],
            ["Safety supervision", "Independent and deterministic", "Limits, E stops, STO, contactors, watchdogs", "Must remain available when AI compute fails"],
          ],
          note: "Rates are architectural ranges. Actual values differ by robot, task, motor, network, and controller design.",
        },
        {
          title: "Compute and Control Suppliers",
          columns: ["Layer", "Representative Companies", "Public Evidence"],
          rows: [
            ["AI compute", "NVIDIA, Qualcomm, AMD, Intel", "Thor adoption or evaluation is publicly disclosed for several makers. Intel and NVIDIA options appear in Unitree and Fourier products."],
            ["Real time MCU", "TI, STMicroelectronics, Infineon, NXP, Renesas", "All publish robotics or humanoid design resources. Exact OEM chips are usually private."],
            ["Servo control", "Synapticon, Elmo Motion Control, Copley, maxon", "Integrated motion products are commercially available; platform relationships vary."],
            ["Industrial control", "Beckhoff, Siemens, B&R, Codesys ecosystem", "Useful for test, safety, and cell integration; onboard use is platform dependent."],
            ["Safety control", "Pilz, Beckhoff TwinSAFE, Siemens, SICK, Synapticon", "Agility confirms safety PLC and FSoE but does not identify the PLC vendor."],
          ],
        },
      ],
    },
    {
      heading: "9. Two Nervous Systems and One Electrical Circulation",
      paragraphs: [
        "A useful humanoid architecture separates three traffic classes. High bandwidth perception carries camera, lidar, audio, and tactile streams toward the main computer. Deterministic control carries synchronized targets and encoder feedback among the whole body controller and joint drives. Safety traffic carries E stop state, limit checks, watchdogs, and certified stop commands. Power distribution runs alongside all three but must be electrically managed so motor switching noise does not corrupt delicate sensors.",
        "Cameras may use MIPI, GMSL2, USB, or Gigabit Ethernet. Motion systems often use EtherCAT or CAN FD. EtherCAT distributed clocks support synchronized control across many axes, while Safety over EtherCAT can carry certified safety data through a black channel architecture. Wireless links are valuable for telemetry, updates, remote assistance, and fleet coordination, but they should not be the sole path for the fastest balance or emergency functions.",
        "The main DC bus commonly feeds local inverters at each joint. Separate converters create rails for compute, sensors, networking, fans, and logic. Grounding, isolation, shield termination, common mode current, and return path design matter because each motor drive is a fast electrical switch sitting next to encoders, cameras, microphones, and touch sensors.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/cable-harness.png",
        alt: "Transparent humanoid body showing power, motor, sensor, camera, control, and safety cable routes through hollow joints and flex zones.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "Data and Power Planes",
          columns: ["Plane", "Typical Interfaces", "Priority", "Should Not Depend On"],
          rows: [
            ["Perception", "MIPI CSI, GMSL2, USB, Gigabit Ethernet", "Bandwidth, synchronization, low latency", "A safety stop decision that must survive AI failure"],
            ["Motion", "EtherCAT, CAN FD, deterministic Ethernet", "Bounded latency, distributed clocks, fault detection", "Cloud availability or nondeterministic model inference"],
            ["Safety", "Hardwired I/O, FSoE, safety fieldbus, redundant channels", "Independent authority and diagnostic coverage", "The normal application process"],
            ["Telemetry", "WiFi, private cellular, Ethernet", "Fleet monitoring, logs, remote support", "Local balance and immediate hazard response"],
            ["High power", "Battery bus and motor phase conductors", "Low loss, safe interruption, insulation", "Sensitive signal grounds or unshielded sensor routing"],
            ["Low voltage", "Converted rails for compute, sensing, logic, and fans", "Stable power, sequencing, isolation", "Uncontrolled regenerative or motor noise"],
          ],
        },
      ],
    },
    {
      heading: "10. Cable Harnesses: The Quiet Reliability Bottleneck",
      paragraphs: [
        "A humanoid cable is asked to bend, twist, slide, and survive impact millions of times in a space too small for the ideal bend radius. Shoulders, elbows, wrists, hips, knees, ankles, and fingers are hostile zones. Copper work hardens. Insulation abrades. shields fracture. Connectors fret. Service loops snag. A single intermittent conductor can look like a software fault, an encoder failure, or a motor problem.",
        "Good architecture reduces how many conductors cross each joint, routes through hollow shafts, controls the neutral bend axis, separates motor phases from encoder and camera lines, adds real strain relief, and places connectors at replaceable module boundaries. Flexible printed circuits help in thin regions. Hybrid connectors can combine power and data. Local electronics reduce wire count, but they add heat and can create another failure node.",
        "Figure's BMW deployment makes this tangible. Figure says the Figure 02 forearm became its leading hardware failure area. A distribution board and dynamic cabling connected the main computer to wrist actuators. Figure 03 removed the board and dynamic wrist cabling so motor controllers communicate more directly with the main computer. That is an anatomy lesson with commercial consequences: every connector and flexing conductor has a failure probability.",
      ],
      tables: [
        {
          title: "Harness Design Checklist",
          columns: ["Design Question", "Good Practice", "Failure Being Prevented"],
          rows: [
            ["How does the joint move?", "Model bend, twist, sliding, and full service pose", "Hidden overtravel and conductor fatigue"],
            ["Where is the neutral axis?", "Constrain the cable path and respect minimum bend radius", "Kinking and unpredictable strain"],
            ["What crosses the joint?", "Reduce conductors through local networking or hollow routing", "Bulk, snagging, and excess terminations"],
            ["How is load removed from pins?", "Use clamps, boots, overmold, and strain relief", "Cracked solder joints and pulled contacts"],
            ["How is noise controlled?", "Separate phases, twist pairs, shield, and design returns", "Encoder jitter, camera errors, tactile noise"],
            ["How is a limb replaced?", "Place keyed, touch safe connectors at module boundaries", "Long repair time and incorrect reconnection"],
            ["How is life validated?", "Test representative motion, temperature, contamination, and current", "Passing a simple flex test that misses real failures"],
          ],
        },
        {
          title: "Harness and Connector Suppliers",
          columns: ["Company", "Relevant Capability", "Evidence Class"],
          rows: [
            ["Molex", "Compact board, signal, power, circular, flexible, and hybrid interconnect portfolio for humanoids", "Commercial supplier"],
            ["TE Connectivity", "Power, signal, data, hybrid connectors, relays, contactors, filters, and sensors positioned for humanoids", "Commercial supplier"],
            ["Amphenol", "High speed, power, circular, sealed, and rugged interconnects", "Commercial supplier"],
            ["Hirose", "Compact board, FPC, coaxial, and humanoid application interconnect map", "Commercial supplier"],
            ["Samtec and LEMO", "High density board and rugged circular connections", "Commercial suppliers"],
            ["igus and LAPP", "Continuous flex and torsion rated robotic cables", "Commercial suppliers"],
            ["Figure", "Public wrist harness simplification between F02 and F03", "Confirmed OEM architecture lesson; cable vendors private"],
          ],
        },
      ],
    },
    {
      heading: "11. Eyes, Depth, Lidar, and the Inner Ear",
      paragraphs: [
        "Humanoids need overlapping views rather than one pair of eyes. Head cameras support navigation and broad manipulation. Wrist or palm cameras look around the arm and into the final centimeters of a grasp. Depth sensing estimates geometry. Lidar provides robust ranging over a wide field. Fisheye cameras reduce blind zones. An inertial measurement unit measures angular velocity and linear acceleration when vision blurs, becomes occluded, or loses features.",
        "Stereo vision triangulates depth from two synchronized views. Active stereo adds projected texture in difficult indoor scenes. Time of flight measures photon travel time. Lidar scans or distributes laser measurements around the robot. Each modality fails differently. Stereo can struggle with textureless, transparent, reflective, very close, or sunlit surfaces. Lidar provides sparse geometry and may struggle with reflectivity or close range. Cameras provide color and semantic detail but depend on exposure, cleanliness, timing, and calibration.",
        "Unitree's public repositories identify a RealSense D435i head camera and Livox MID 360 lidar in G1 configurations, with a RealSense D405 available at the wrist. This is rare named sensor evidence. Figure says its current vision architecture doubles frame rate, cuts latency to one quarter, expands field of view by 60 percent per camera, and adds palm cameras, but it keeps sensor vendors private. Boston Dynamics lists 360 degree camera coverage on Atlas. Exact optical bills of materials remain private across most platforms.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/perception-sensors.png",
        alt: "Humanoid head and perception modules showing stereo cameras, depth optics, lidar, side cameras, wrist and palm cameras, IMU, microphones, and speaker.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "Perception Organ Comparison",
          columns: ["Sensor", "What It Adds", "Primary Weakness", "Representative Companies"],
          rows: [
            ["Global shutter RGB", "Texture, color, semantics, motion without rolling distortion", "Lighting, exposure, occlusion, lens contamination", "Sony, onsemi, OmniVision, Basler, IDS"],
            ["Stereo depth", "Passive or active metric geometry from paired views", "Texture, sunlight, reflective and transparent surfaces", "RealSense, Stereolabs, Luxonis, Orbbec"],
            ["Time of flight", "Compact direct depth measurement", "Multipath, ambient light, range and resolution", "Analog Devices, Infineon, Orbbec, Sony"],
            ["Lidar", "Wide field geometry across varied illumination", "Sparse semantics, reflectivity, close range, cost", "Ouster, Livox, Hesai, RoboSense"],
            ["Event camera", "Very low latency brightness change and high dynamic range", "Different data representation and integration complexity", "Prophesee"],
            ["IMU", "Fast body rotation and acceleration", "Bias, vibration, thermal drift, integration error", "Bosch Sensortec, TDK InvenSense, Analog Devices"],
            ["Palm and wrist cameras", "Close view of grasp and occluded work area", "Cable flex, impacts, small baseline, contamination", "OEM internal modules; RealSense, Orbbec, Stereolabs candidates"],
          ],
        },
      ],
    },
    {
      heading: "12. Proprioception, Force, Touch, Hearing, and Voice",
      paragraphs: [
        "Proprioception lets the robot estimate its own body. Motor and output encoders provide joint position. Motor current estimates commanded torque. Physical torque sensors measure strain in a calibrated element. Wrist and ankle force torque sensors recover the full three dimensional force and moment at a contact. Temperature, voltage, and current reveal stress that geometry alone cannot see.",
        "Motor current is a useful force estimate but contains friction, gearbox losses, temperature effects, cogging, and dynamic error. Direct torque sensing adds weight and calibration but improves compliant interaction. A series elastic actuator intentionally introduces a known deflection that acts as both spring and force measurement. No method is free: stiffness, bandwidth, shock survival, and accuracy trade against each other.",
        "PAL TALOS is a useful research anatomy reference because it exposes joint torque sensing, six axis force torque sensors at wrists and ankles, high rate inertial sensing, encoders, temperature, and EtherCAT control. ATI and Bota Systems supply compact multiaxis force torque technology. XELA, GelSight, Touchlab, Shadow Robot, and other specialists address the far denser problem of touch across fingers and skin.",
        "Audio is both an interface and a sensor. A microphone array estimates direction, supports beamforming, and helps the robot hear through factory noise, motor whine, fans, and its own footsteps. Acoustic echo cancellation is required if the robot speaks while listening. Unitree discloses a four microphone array and 5 W speaker on G1. Figure describes a larger speaker and repositioned microphone. The underlying acoustic component vendors remain private.",
      ],
      tables: [
        {
          title: "Sensing the Self and Contact",
          columns: ["Measurement", "Hardware", "Best Use", "Caveat"],
          rows: [
            ["Rotor position", "Magnetic, inductive, or optical motor encoder", "Commutation and fast speed control", "Does not include reducer error"],
            ["Joint output angle", "Absolute output encoder", "True link pose after the transmission", "Resolution does not equal installed accuracy"],
            ["Joint torque", "Strain flexure, series elastic deflection, or observer", "Impedance and collision response", "Temperature, friction, and calibration matter"],
            ["Wrist load", "Six axis force torque transducer", "Compliant manipulation and payload estimation", "Overload survival and tool offset calibration"],
            ["Ground load", "Ankle or foot force torque sensor", "Balance and center of pressure", "Shock load and mounting stiffness"],
            ["Finger contact", "Pressure pad or tactile taxel array", "Grip force and contact location", "Coverage gaps and drift"],
            ["Slip and texture", "Three axis or optical tactile sensor", "Dexterous grasp correction", "Elastomer wear, compute, and contamination"],
            ["Voice direction", "Synchronized MEMS microphone array", "Barge in, localization, interaction", "Self noise and echo cancellation"],
          ],
        },
      ],
    },
    {
      heading: "13. Thermal Homeostasis: Turning Peak Performance Into Shift Work",
      paragraphs: [
        "Every important humanoid organ creates heat. Copper losses warm motor windings. Inverters dissipate switching and conduction losses. Reducers and bearings create friction. The AI computer consumes continuous power. Battery resistance generates heat during hard discharge, regeneration, and charging. Brakes, converters, radios, and even dense tactile electronics add smaller thermal loads.",
        "The usual path runs from winding or semiconductor, through insulation and thermal interface material, into a housing, frame, heat pipe, cold plate, or fin, then into ambient air. The most elegant design uses structural metal as a heat spreader. The most serviceable design still lets a technician replace the module without destroying its thermal interface or calibration.",
        "Passive cooling is quiet and has fewer failure points, but it depends on surface area, temperature difference, and airflow around the body. Forced air removes more heat but adds fans, noise, filters, ingestion risk, and parasitic power. Liquid cooling can concentrate heat rejection but introduces pumps, seals, manifolds, and leak risk. Many humanoids mix methods: passively cooled joint housings, forced air compute, and an actively cooled battery.",
        "Boston Dynamics says Atlas actuators use passive cooling and external fins, with a fan in the head. Figure integrates active cooling into the battery structure. Unitree highlights heat dissipation in its internal rotor joint design. The broader lesson is simple: peak torque, peak compute, and fast charging cannot be used continuously unless the complete body can reject the combined heat.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/thermal-management.png",
        alt: "Humanoid thermal map with heat in motors, compute, battery, and joints plus cooling fins, heat pipes, cold plates, fans, and thermal interface materials.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "Thermal Organs and Their Limits",
          columns: ["Heat Source", "Cooling Path", "What Degrades First", "Design Test"],
          rows: [
            ["Motor winding", "Stator to housing to link and air", "Continuous torque and insulation life", "Worst joint pose at repeated duty cycle"],
            ["Servo inverter", "Semiconductor to board and housing", "Current limit, switching efficiency, capacitor life", "Peak phase current at hot ambient"],
            ["Reducer and bearing", "Lubricant and metal interfaces to housing", "Efficiency, grease life, backlash", "Long duration oscillation and shock"],
            ["AI compute", "Heat spreader, heat pipe, fin stack, fan", "Clock rate and inference latency", "All sensors and largest deployed model at once"],
            ["Battery discharge", "Cells to holders, gap filler, cold plate, enclosure", "Voltage sag, cell life, protection margin", "Walking, lifting, recovery, and regen profile"],
            ["Fast charging", "Cells and charge electronics to active cooling", "Charge rate and fleet availability", "Hot pack after work entering unattended charge"],
            ["External skin", "Internal heat through padding and covers", "Safe touch temperature and hidden hotspots", "Blocked vents, dirty filters, damaged foam"],
          ],
        },
        {
          title: "Thermal Supplier Landscape",
          columns: ["Category", "Representative Companies", "Typical Contribution"],
          rows: [
            ["Thermal interface materials", "Henkel, 3M, Parker Chomerics, Laird", "Pads, gels, gap fillers, adhesives, electrically insulating heat paths"],
            ["Cold plates and liquid hardware", "Boyd, Modine, Parker", "Custom plates, manifolds, compact liquid cooling"],
            ["Fans and blowers", "Delta Electronics, ebm papst, Sunon, Nidec", "Compute and enclosure airflow"],
            ["Heat pipes and vapor chambers", "Boyd, Wakefield, Asia Vital Components", "Move heat from compact compute to usable surface area"],
            ["Thermally conductive polymers", "Covestro, BASF, Celanese", "Light enclosures and heat spreading structures"],
            ["OEM integration", "Figure, Boston Dynamics, Unitree, 1X, Apptronik", "Body level co design; exact vendors generally private"],
          ],
        },
      ],
    },
    {
      heading: "14. Skin, Seals, and the Independent Safety Reflex",
      paragraphs: [
        "The visible shell does more than create a face. Hard covers block debris and distribute impact. Foam lowers contact pressure. Textiles hide gaps while remaining washable and replaceable. Bellows and boots prevent pinch access. Seals retain lubricant and protect bearings and electronics. Optical windows protect lenses without destroying image quality. The final skin must survive repeated cleaning, abrasion, sweat, oils, dust, and collisions.",
        "Softness can reduce injury severity, but it does not replace control safety. A padded robot can still trap a person, drop a payload, fall, or move a joint with high energy. Safe design combines limited inertia, rounded geometry, compliant control, speed and force limits, verified stopping, protective sensing, emergency stops, safe torque off, brakes, contactors, diagnostics, and operational procedures.",
        "The safety reflex must be able to override the main AI system. A safety PLC or equivalent controller reads independent E stops, limit channels, protective devices, drive status, and watchdogs. It can request a controlled stop, remove motor torque through STO, apply brakes where designed, and open the high power path. Redundancy without diversity can still fail from a shared connector, power rail, software defect, or physical impact, so common cause analysis matters.",
        "Agility publicly describes a safety PLC, on robot and pendant E stops, a Category 1 stop, Safety over EtherCAT, and functions designed to Performance Level d on Digit. Boston Dynamics lists Atlas as IP67 with field replaceable modules. Figure uses multidensity foam and washable textiles. 1X uses a soft lattice polymer exterior. These details indicate different safety philosophies, but certification must always be tied to the exact application, configuration, standard, and integration.",
      ],
      visual: {
        src: "/article-images/humanoid-anatomy/safety-skin.png",
        alt: "Humanoid protective layers from frame to foam and textile skin alongside an independent safety controller, E stop, contactor, brake, and human sensing zone.",
        caption: atlasCaption,
      },
      tables: [
        {
          title: "The Safety Reflex Arc",
          columns: ["Stage", "Hardware or Logic", "Purpose", "Verification Question"],
          rows: [
            ["Hazard sensing", "Vision, lidar, safety scanner, tactile, force limits", "Detect people, obstacles, contact, or abnormal load", "What faults can create a missed detection?"],
            ["Independent input", "Dual channel E stop, enable device, hard limits", "Give people and hardware direct authority", "Can one broken wire mask the demand?"],
            ["Safety decision", "Safety PLC, safe MCU, certified drive logic", "Evaluate limits and select stop behavior", "Is it independent from the AI application?"],
            ["Controlled stop", "Motion controller with monitored deceleration", "Reduce kinetic energy without losing balance", "What happens during network or compute loss?"],
            ["Torque removal", "STO at the drives", "Prevent active torque production", "Is dangerous stored energy still present?"],
            ["Mechanical retention", "Holding brake, counterbalance, stops", "Manage gravity loaded axes", "Will the body or payload fall after STO?"],
            ["Power isolation", "Redundant contactors, discharge path, weld detection", "Open the high energy bus", "Can a welded contact be detected and contained?"],
            ["Recovery", "Reset, diagnostics, supervised restart", "Prevent unexpected return to motion", "Who confirms the workspace is safe?"],
          ],
        },
        {
          title: "Standards Context",
          columns: ["Reference", "Where It Helps", "Important Limit"],
          rows: [
            ["ISO 10218 series", "Industrial robots and robot systems", "A mobile dynamically balancing humanoid may introduce hazards beyond a traditional fixed arm"],
            ["ISO TS 15066", "Collaborative industrial robot applications", "Application limits and contact evaluation still depend on the complete system"],
            ["ISO 13482", "Personal care robot safety", "Scope differs from industrial and medical applications"],
            ["IEC 61508", "Functional safety foundation", "A capable component does not certify the final robot"],
            ["ISO 13849", "Safety related control system performance", "Performance Level requires architecture, diagnostics, validation, and application evidence"],
            ["IEC 61800 5 2", "Safe drive functions such as STO", "Drive safety does not resolve falling, payload, navigation, or grasp hazards"],
          ],
          note: "The applicable framework depends on where and how the robot is used. Buyers should demand a documented hazard analysis and certification scope for the exact deployed configuration.",
        },
      ],
    },
    {
      heading: "15. Comparative Anatomy of Leading Humanoids",
      paragraphs: [
        "Humanoids that look similar can have radically different internal priorities. Some maximize industrial payload and ingress protection. Some minimize weight for home contact. Some use swappable packs for continuous operations. Some trade work readiness for low cost research access. Published specifications also use different definitions, so payload, runtime, degree of freedom count, and compute cannot be compared without reading the method.",
        "The table below uses publicly disclosed 2026 information and preserves uncertainty. A blank or private specification is more honest than carrying an older generation number into a current product.",
      ],
      tables: [
        {
          title: "Representative Platform Anatomy",
          columns: ["Platform", "Body and Power", "Sensing and Compute", "Anatomical Signature"],
          rows: [
            ["Figure 03", "1.73 m, 61 kg, 20 kg payload, 2.3 kWh structural battery, stated 5 hour runtime", "Internal vision and tactile architecture; palm cameras; compute vendor private", "High internal design control, structural pack, wireless foot charging, manufacturing redesign"],
            ["Apptronik Apollo", "1.72 m, 72.6 kg, 25 kg lift and carry; swappable batteries", "Head and torso perception; chest computer; exact vendors private", "Linear and rotary force controlled actuators, modular power, Jabil manufacturing relationship"],
            ["Agility Digit", "About 1.75 m, 63.5 kg, 15.9 kg carry, 4 hour battery, 28 degrees of freedom", "Jetson in current generation path; Thor planned for later generation", "Logistics first body, interchangeable end effectors, autonomous docking, disclosed safety stack"],
            ["Boston Dynamics Atlas", "1.9 m, 90 kg, 56 degrees of freedom, 4 hour nominal runtime, IP67", "360 degree camera coverage, tactile hands, Jetson Thor integration", "High mobility, modular common actuators, passive joint cooling, automated battery swap"],
            ["Unitree G1", "1.32 m, about 35 kg, 23 to 43 joint motors, about 2 hours, 13 series battery", "Eight core CPU, depth camera, lidar, optional Orin class compute", "Low entry price, compact research body, dual encoder hollow joint routing"],
            ["Unitree H1 2", "1.78 m, 70 kg, 27 degrees of freedom, 864 Wh pack", "Intel control compute, up to three optional Orin NX modules, lidar and depth", "Speed and high torque leg architecture with growing manipulation capability"],
            ["1X NEO", "1.68 m, 29.9 kg, 842 Wh, stated 4 hour runtime, soft lattice body", "Jetson Thor product path and remote expert assistance", "Low inertia tendon drive, soft home oriented exterior, 25 degree of freedom hand"],
            ["Fourier GR 2", "1.75 m, 63 kg, up to 53 joints, 950 Wh, about 2 hours", "Intel motion computer, ARM perception computer, stereo camera, IMU", "Research orientation, internal FSA actuators, optional tactile hands"],
            ["UBTECH Walker S2", "1.76 m, about 70 kg excluding hands, 52 degrees of freedom, dual batteries", "X86 plus Jetson Orin, stereo, depth, fisheye, IMU, force torque sensing", "Autonomous three minute battery swap and continuous industrial operating thesis"],
            ["PAL TALOS", "1.75 m, 95 kg, 32 degrees of freedom, 1,080 Wh battery", "Joint torque, wrist and ankle force torque, high rate IMU and EtherCAT", "Research grade whole body torque control with unusually transparent sensing anatomy"],
            ["Tesla Optimus Gen 3", "Current production design specifications not publicly complete", "Tesla vision and planning architecture; current robot chip and sensor BOM private", "Maximum vertical integration thesis with incomplete public component detail"],
          ],
          note: "Payload definitions and runtime test conditions differ. Figures are not a ranking and should be verified against the current configuration before procurement.",
        },
      ],
    },
    {
      heading: "16. Master Component and Supplier Atlas",
      paragraphs: [
        "The humanoid value chain is not one new industry. It joins automotive batteries and electronics, industrial motion control, machine vision, precision bearings and transmissions, mobile robotics, safety engineering, contract manufacturing, and AI compute. The table maps the major organs to companies that can credibly occupy each layer.",
        "Only the evidence column establishes whether a supplier belongs to a named robot. Where the status says commercial supplier, the company has an appropriate portfolio but the target OEM relationship is not claimed.",
      ],
      tables: [
        {
          title: "Mechanical and Motion Supplier Atlas",
          columns: ["Organ", "Companies", "Evidence and Role"],
          rows: [
            ["Integrated actuators", "Schaeffler, Synapticon, maxon, TQ RoboDrive, Kollmorgen, Moog", "Schaeffler has disclosed Humanoid partnerships; maxon components are confirmed in Reachy 2; others are commercial suppliers"],
            ["Frameless motors", "maxon, Kollmorgen, TQ RoboDrive, Moog, Schaeffler", "Commercial motor suppliers; current flagship OEM content usually private"],
            ["Strain wave gearing", "Harmonic Drive, Schaeffler, Leaderdrive, Nabtesco", "Schaeffler and Humanoid is a confirmed partnership; others are commercial suppliers"],
            ["Planetary gearing", "maxon, Schaeffler, Neugart, Wittenstein, Nidec", "maxon GPX is documented in Reachy 2; broader platform ties vary"],
            ["Cycloidal gearing", "Nabtesco, Sumitomo Drive Technologies, Spinea", "Commercial supplier category"],
            ["Linear screws and actuators", "Schaeffler, THK, Bosch Rexroth, Ewellix, HIWIN, Rollvis", "Commercial suppliers; OEM linear actuator details remain private"],
            ["Bearings", "Schaeffler, SKF, THK, NSK, NTN, Timken, IKO", "Commercial suppliers; Unitree confirms crossed roller architecture but not its vendor"],
            ["Encoders", "RLS, HEIDENHAIN, Renishaw, ams OSRAM, Celera Motion, Netzer", "RLS is documented on PAL REEM C; most modern OEM ties private"],
            ["Brakes", "mayr, Miki Pulley, Kendrion", "Commercial compact safety brake suppliers"],
            ["Hands", "Shadow Robot, SCHUNK, Tesollo, Wonik, qb robotics, Inspire Robots, Seed Robotics", "PAL confirms Inspire and Seed options; others are commercial platforms"],
            ["Soles and elastomers", "Vibram, BASF, Covestro, Trelleborg", "Vibram and Agility is confirmed; BASF and Fourier is a development relationship"],
            ["Seals and boots", "Trelleborg, Freudenberg, Parker", "Commercial supplier category; modern target OEM content private"],
          ],
        },
        {
          title: "Electrical, Compute, and Sensor Supplier Atlas",
          columns: ["Organ", "Companies", "Evidence and Role"],
          rows: [
            ["Battery cells", "CATL, LG Energy Solution, Samsung SDI, Molicel, Panasonic Energy, EVE Energy", "CATL and Galbot confirmed; Samsung and Hyundai Kia development confirmed; most OEM cell vendors private"],
            ["BMS and power silicon", "TI, Analog Devices, NXP, Infineon, Renesas, STMicroelectronics", "All offer suitable components or humanoid reference material; exact OEM chips private"],
            ["Contactors and protection", "Sensata, TE, Littelfuse, Eaton", "Commercial supplier category"],
            ["DC conversion", "Vicor, Murata, TDK Lambda, Delta Electronics", "Commercial supplier category"],
            ["AI compute", "NVIDIA, Qualcomm, AMD, Intel", "NVIDIA has several disclosed humanoid relationships; Intel and NVIDIA options appear in named platforms"],
            ["Real time control", "TI, Infineon, STMicroelectronics, NXP, Renesas", "Commercial processors and reference designs; OEM selection private"],
            ["Servo drives", "Synapticon, Elmo Motion Control, Copley, maxon", "Commercial motion control suppliers"],
            ["RGB and depth cameras", "RealSense, Stereolabs, Luxonis, Orbbec, Basler, IDS", "RealSense modules are documented in Unitree configurations; others are commercial suppliers"],
            ["Image sensors", "Sony, onsemi, OmniVision, SmartSens", "Merchant sensor suppliers; module and OEM relationships often private"],
            ["Lidar", "Livox, Ouster, Hesai, RoboSense", "Livox MID 360 is documented in G1 software; Ouster has a confirmed FieldAI relationship"],
            ["IMU", "Bosch Sensortec, TDK InvenSense, Analog Devices", "Commercial suppliers; exact base IMU vendors mostly private"],
            ["Force torque", "ATI Industrial Automation, Bota Systems", "Commercial suppliers; PAL and IIT disclose sensing architectures but not always an outside vendor"],
            ["Tactile", "XELA, GelSight, Touchlab, Shadow Robot, Pressure Profile Systems, Tekscan", "Commercial suppliers; Figure and Sanctuary use internal designs; Sharpa is confirmed on NVIDIA reference"],
            ["Audio", "Infineon, TDK, Knowles, Seeed Studio", "Commercial microphones and arrays; named robot die vendors private"],
            ["Harness and connectors", "Molex, TE, Amphenol, Hirose, Samtec, LEMO, igus, LAPP", "Commercial humanoid and robotics portfolios; OEM content private"],
            ["Thermal", "Henkel, 3M, Boyd, Parker, Delta, ebm papst, Sunon", "Commercial material and cooling suppliers"],
            ["Safety", "Pilz, Beckhoff, Siemens, SICK, Synapticon", "Agility confirms the architecture but not its safety PLC vendor"],
          ],
        },
        {
          title: "Confirmed Relationships Worth Remembering",
          columns: ["Supplier", "Robot Company or Platform", "Confirmed Scope"],
          rows: [
            ["Schaeffler", "Humanoid", "Development and supply of strain wave actuators for humanoid joints"],
            ["maxon", "Pollen Robotics Reachy 2", "Named motors, encoders, and GPX gearboxes in Orbita joints"],
            ["RLS and Renishaw", "PAL Robotics REEM C", "Named magnetic encoder families in robot joints"],
            ["Vibram", "Agility Robotics Digit", "Purpose developed sole"],
            ["Jabil", "Apptronik Apollo", "Worldwide manufacturing, test, procurement, and supply chain support"],
            ["BASF", "Fourier", "Evaluation and development of polymers for robot components"],
            ["CATL", "Galbot S1", "Battery relationship identified by CATL"],
            ["RealSense and Livox", "Unitree G1 configurations", "D435i or D405 cameras and MID 360 mounts identified in official repositories"],
            ["NVIDIA", "Atlas, Digit, 1X, Figure, H2 reference", "Adoption, planned adoption, evaluation, or confirmed reference integration varies by platform"],
            ["Sharpa", "NVIDIA H2 reference design", "Dual Wave tactile five finger hands"],
          ],
          note: "Relationship scope can change by robot generation and configuration. A confirmed partnership does not establish every component inside the platform.",
        },
      ],
    },
    {
      heading: "17. What Robot Makers Build and What They Buy",
      paragraphs: [
        "The highest differentiation sits at the interfaces. A company may buy an excellent motor, reducer, encoder, and drive, yet still fail if the joint is heavy, hot, noisy, difficult to assemble, or impossible to service. That is why leading OEMs tend to control actuator architecture, battery integration, hand design, structural packaging, calibration, controls, safety, and the learning system even when they purchase many underlying parts.",
        "Merchant components remain essential. Battery cells require enormous electrochemical scale. GPUs and semiconductors require advanced fabrication. Precision bearings, connectors, seals, magnets, passive components, and image sensors benefit from specialized suppliers. Contract manufacturers can industrialize winding, electronics, tooling, test, and procurement without owning the robot architecture.",
        "Figure explicitly says its actuators, batteries, sensors, electronics, and structures are designed internally. Apptronik owns its actuator approach and works with Jabil on manufacturing. Agility controls Digit and operates RoboFab. Boston Dynamics designs and builds Atlas while integrating merchant compute. 1X manufactures motors and actuators around its tendon and soft body thesis. Sanctuary describes a mixed internal and partner ecosystem. The likely mature industry is neither total vertical integration nor pure assembly. It is selective control of the organs that determine behavior, cost, and reliability.",
      ],
      tables: [
        {
          title: "Practical Make Versus Buy Logic",
          columns: ["Usually Control Closely", "Why", "Usually Buy or Co Develop", "Why"],
          rows: [
            ["Actuator packaging and control", "Defines mass, torque, heat, feel, and service", "Motor materials and semiconductor devices", "Specialized scale and process technology"],
            ["Hand and tactile integration", "Manipulation data and mechanics are strategic", "Selected hand modules during research", "Faster learning before internal volume design"],
            ["Battery pack and BMS integration", "Safety, structure, current profile, and charging are body specific", "Electrochemical cells", "Cell manufacturing requires enormous scale"],
            ["Safety architecture", "Must match body dynamics and deployment hazards", "Certified components and external validation", "Evidence and independent assurance matter"],
            ["Whole body controls and calibration", "Creates the platform's motion quality", "Industrial buses, encoders, and MCUs", "Standards and supplier ecosystems reduce reinvention"],
            ["Data, models, and fleet learning", "Compounds with every deployment", "Cloud and training infrastructure", "Capital efficiency and broad tooling"],
            ["Structural and thermal co design", "Every gram and watt propagates through the body", "Materials, adhesives, fans, and thermal interfaces", "Specialist materials science and volume supply"],
            ["End of line test", "Calibration quality defines shipped behavior", "Contract manufacturing execution", "Partners can scale fixtures, procurement, and labor"],
          ],
        },
      ],
    },
    {
      heading: "18. Where the Cost and Value Concentrate",
      paragraphs: [
        "Actuation is usually the largest mechanical value pool because a humanoid may contain dozens of high precision joints. Schaeffler estimates that actuators can represent roughly half of the bill of materials in many humanoids. Its illustrative analysis places significant value in rotary actuators, linear actuators, and hands. This is a supplier estimate, not a universal cost model.",
        "Agility's public transaction materials placed a current Digit generation bill of materials near $125,000. Unitree advertises a far lower G1 entry price because it targets a smaller research platform with different payload, durability, safety, support, compute, and configuration. Prototype platforms, scaled consumer products, and certified industrial systems should never be placed on one cost curve without normalizing what the buyer receives.",
        "Cost reduction will come from architecture as much as supplier negotiation. Fewer actuator sizes, common left and right parts, cast and molded structures, automated winding, shorter harnesses, reduced connector count, modular calibration, higher electronics yield, right sized compute, and field replaceable cartridges can each remove recurring cost. A cheap component that increases assembly time or field failures can raise total cost.",
      ],
      barCharts: [
        {
          title: "Illustrative Value Concentration by System",
          maxValue: 50,
          unit: "% directional share",
          bars: [
            { label: "Actuation and joints", value: 50, detail: "Directional supplier estimate. Includes motors, transmissions, bearings, sensing, and integration." },
            { label: "Perception and compute", value: 18, detail: "Camera, lidar, inertial sensing, AI compute, networking, and memory can vary widely by platform." },
            { label: "Structure and skin", value: 14, detail: "Materials and processes move from machined prototypes toward cast, stamped, molded, and textile parts." },
            { label: "Power system", value: 10, detail: "Cells are only part of the pack; BMS, protection, cooling, structure, and charging add value." },
            { label: "Harness, safety, and controls", value: 8, detail: "Often underestimated in cost models despite a large effect on assembly and uptime." },
          ],
          note: "This visualization synthesizes broad industry ranges and Schaeffler's actuation estimate. It is not a disclosed bill of materials for any named robot and should not be used as a procurement quote.",
        },
      ],
      tables: [
        {
          title: "The Cost Down Levers That Matter",
          columns: ["Lever", "Factory Effect", "Field Effect", "Hidden Risk"],
          rows: [
            ["Common actuator families", "Fewer tools, fixtures, tests, and stocked parts", "Simpler spares and training", "Oversized joints can waste mass and power"],
            ["Cast, stamped, and molded structure", "Lower unit cost after tooling", "More consistent geometry", "Tooling changes become expensive"],
            ["Shorter harness and fewer connectors", "Less manual routing and test", "Fewer intermittent failures", "Overcentralization can make module replacement harder"],
            ["Automated calibration", "Higher throughput and repeatability", "Better replacement consistency", "Poor reference fixtures can scale error"],
            ["Right sized compute", "Lower module and cooling cost", "Lower power and heat", "Insufficient memory or model headroom"],
            ["Replaceable cartridges", "Module level test before assembly", "Shorter mean time to repair", "Connector and sealing complexity"],
            ["Supplier dual sourcing", "Resilience and price pressure", "Part availability", "Calibration and software variation across alternates"],
          ],
        },
      ],
    },
    {
      heading: "19. Failure Anatomy: What Breaks Before the Demo Ends",
      paragraphs: [
        "A laboratory demonstration rewards peak capability. A commercial deployment rewards ordinary repetition. The failure that stops a fleet may be a wrist cable, worn sole, dirty lens, drifting tactile pad, hot inverter, loose fastener, or calibration record rather than the foundation model.",
        "Failures also cascade. Bearing wear changes joint friction. The torque observer becomes biased. The controller compensates with more current. Motor and inverter temperature rise. Battery consumption increases. Motion quality falls. If health monitoring watches only individual components, it can miss the system level pattern.",
      ],
      tables: [
        {
          title: "Failure Mode Atlas",
          columns: ["Organ", "Failure Mode", "Early Signal", "Design or Maintenance Response"],
          rows: [
            ["Frame", "Crack, loosened fastener, interface deformation", "Changing alignment, vibration, torque offset", "Fatigue analysis, witness marks, torque audit, nondestructive inspection"],
            ["Motor", "Winding insulation or magnet damage", "Rising resistance, heat, torque loss", "Thermal model, current derating, winding test"],
            ["Reducer", "Backlash, tooth or flexspline fatigue, grease loss", "Dual encoder disagreement, noise, ripple", "Shock limits, lubrication plan, health trending, cartridge replacement"],
            ["Bearing", "Pitting, brinelling, contamination", "Vibration, temperature, friction", "Correct preload, sealing, impact control, replacement interval"],
            ["Brake", "Failure to release or hold", "Current change, drag, position creep", "Proof test, redundant strategy, safe collapse analysis"],
            ["Encoder", "Drift, contamination, lost counts, mounting slip", "Residual against second encoder and kinematics", "Absolute reference, plausibility checks, recalibration"],
            ["Torque sensor", "Thermal zero shift or overload", "Bias with unloaded joint", "Temperature compensation, overload stops, automatic zero validation"],
            ["Tendon", "Stretch, creep, fray, pulley wear", "Position hysteresis and rising motor travel", "Tension monitoring, replaceable routing, scheduled service"],
            ["Tactile skin", "Puncture, delamination, drift, contamination", "Dead taxels, baseline shift, inconsistent slip", "Replaceable pads, calibration, cleaning protocol, sensor redundancy"],
            ["Foot sole", "Wear, hardening, contamination", "Changed pressure signature and slip frequency", "Replaceable tread, friction inspection, policy adjustment"],
            ["Battery cell", "Imbalance, resistance rise, internal fault", "Voltage spread, heat, reduced usable energy", "Cell monitoring, propagation barriers, pack retirement criteria"],
            ["Contactor", "Weld or failure to close", "Auxiliary contact mismatch, abnormal bus voltage", "Precharge, weld detection, redundant isolation"],
            ["Harness", "Copper fatigue, fretting, abrasion, loose retention", "Intermittent faults tied to joint pose", "Motion representative flex test, strain relief, module connectors"],
            ["Camera", "Dirty window, exposure failure, calibration movement", "Reduced confidence, reprojection residual", "Cleaning, health image, redundant view, calibration check"],
            ["Lidar", "Blocked aperture or timing fault", "Coverage holes and range anomalies", "Window cleaning, plausibility fusion, safe degraded mode"],
            ["IMU", "Bias, vibration coupling, clock offset", "State estimator residual and drift", "Rigid mount, isolation, thermal calibration, synchronized time"],
            ["Compute", "Thermal throttling, memory exhaustion, storage fault", "Latency tail and missed deadlines", "Resource partitioning, watchdog, degraded model, cooling service"],
            ["Network", "Clock drift, packet loss, connector fault", "Jitter, cyclic error counters", "Distributed clock monitoring, redundant path where justified"],
            ["Safety system", "Nuisance trip or dangerous missed demand", "Diagnostic event or failed proof test", "Independent validation, proof testing, common cause analysis"],
            ["Software update", "Timing, calibration, or behavior regression", "Longer latency and changed fault distribution", "Versioned configuration, staged rollout, rollback, acceptance test"],
          ],
        },
      ],
    },
    {
      heading: "20. Manufacturing, Calibration, and Service Anatomy",
      paragraphs: [
        "A robot is not ready for scale when one expert can assemble it. It is ready when normal technicians can build, calibrate, test, repair, and return it to service with predictable tools and time. Manufacturing quality becomes control quality because encoder alignment, bearing preload, tendon tension, motor phase calibration, camera extrinsics, foot geometry, and torque zeros all enter the software model.",
        "Module level testing is powerful. A joint cartridge can be tested for current, torque, friction, backlash, encoder agreement, brake operation, leakage, temperature, and vibration before it enters the body. A limb can store its own serial number and calibration. A replacement then becomes a controlled exchange rather than a mechanical rebuild inside the customer site.",
        "Boston Dynamics emphasizes Atlas commonality and field replaceable modules. Figure redesigned around production processes and eliminated known forearm failure architecture. Jabil provides Apptronik manufacturing, test, procurement, and supply chain support. Agility operates RoboFab with stated capacity as high as 10,000 robots annually. These examples show that the humanoid race is becoming a manufacturing and service race.",
      ],
      tables: [
        {
          title: "End of Line Examination",
          columns: ["Station", "What Is Measured", "Why It Matters in the Field"],
          rows: [
            ["Joint characterization", "Torque constant, friction, backlash, encoder offset, temperature", "Controller receives the real joint rather than an ideal model"],
            ["Limb calibration", "Axis geometry, kinematics, force zero, cable behavior", "Replacement limbs preserve whole body accuracy"],
            ["Vision calibration", "Intrinsics, extrinsics, synchronization, focus, optical cleanliness", "Depth, grasp, and navigation share one coordinate system"],
            ["Battery and power test", "Capacity, impedance, protection, precharge, contactor, insulation", "High energy faults are found before shipment"],
            ["Network timing", "Cycle time, jitter, clock agreement, error counters", "Balance and sensing remain deterministic"],
            ["Safety validation", "E stop, limits, STO, brakes, contactors, restart", "The actual built unit reaches the intended safe state"],
            ["Whole body acceptance", "Walking, contact, payload, thermal soak, recovery", "Interactions among otherwise good modules are exposed"],
            ["Configuration record", "Hardware revision, firmware, calibration, model, service history", "Fleet failures can be traced and updates controlled"],
          ],
        },
        {
          title: "Service Metrics That Belong Beside Payload",
          columns: ["Metric", "What It Reveals"],
          rows: [
            ["Mean time between mission affecting failures", "How long the complete robot performs useful work"],
            ["Mean time to diagnose", "Whether faults identify the real organ instead of generating ambiguous alarms"],
            ["Mean time to repair", "Modularity, access, tools, connectors, calibration, and spare strategy"],
            ["Intervention rate", "How frequently a person rescues the autonomy or hardware"],
            ["Spare consumption per thousand hours", "True wear and reliability economics"],
            ["Energy per useful task", "Body efficiency rather than idle runtime"],
            ["Thermal derating time", "Difference between peak demonstration and sustained work"],
            ["Calibration retention", "Whether transport, impact, and module replacement change behavior"],
          ],
        },
      ],
    },
    {
      heading: "21. A Buyer's Dissection Checklist",
      paragraphs: [
        "A humanoid should be purchased around a paid task, not around a body shape. Start with the work object, route, force, cycle, environment, exception rate, and safety boundary. Then trace every organ required to complete that task repeatedly.",
        "A buyer does not need the confidential supplier name for every screw. The buyer does need enough architecture, test evidence, spares, telemetry, and support terms to understand failure consequences and operating cost. The strongest vendors can explain what the robot does when a camera is blocked, a tactile pad drifts, a joint overheats, a network link drops, a battery faults, or the main computer reboots.",
      ],
      tables: [
        {
          title: "Technical Due Diligence",
          columns: ["Domain", "Questions to Ask"],
          rows: [
            ["Task definition", "What exact objects, weights, poses, cycle times, routes, and exceptions are included?"],
            ["Actuators", "What are continuous torque, thermal duration, shock limits, backlash, life test, and replacement time?"],
            ["Hands", "What grasps are validated, what tactile coverage exists, and how often are fingers, tendons, or pads replaced?"],
            ["Battery", "What is usable energy, peak current, runtime at this task, charge time, cycle life, transport status, and fault containment?"],
            ["Compute", "Which models run onboard, at what latency and power, with what memory headroom and degraded mode?"],
            ["Perception", "What happens in glare, darkness, dust, reflective packaging, transparent objects, occlusion, and dirty optics?"],
            ["Control", "Which loops run locally, what are their rates, how is time synchronized, and what happens during packet loss?"],
            ["Safety", "Which standard and configuration are assessed, what safe states exist, and who owns site integration validation?"],
            ["Reliability", "What are fleet hours, task hours, intervention rate, component failures, and thermal derating data?"],
            ["Service", "Which modules are field replaceable, what tools and calibration are required, and where are spares stocked?"],
            ["Cybersecurity", "How are identity, signed software, remote access, logs, secrets, rollback, and vulnerability response managed?"],
            ["Data rights", "Who owns video, tactile, intervention, failure, and derived training data from the site?"],
          ],
        },
        {
          title: "A Disciplined Pilot Sequence",
          columns: ["Phase", "Proof Required Before Advancing"],
          rows: [
            ["Bench anatomy", "Component limits, hazard analysis, service access, and interface documentation are understood"],
            ["Controlled workcell", "One task completes safely with measured cycle time, quality, intervention, and heat"],
            ["Representative shift", "Battery, charging, thermal behavior, wear, and support survive the real schedule"],
            ["Exception campaign", "The robot handles or safely escalates common failures and edge cases"],
            ["Maintenance trial", "Site staff diagnose, exchange modules, recalibrate, and return the robot to work"],
            ["Small fleet", "Fleet software, spares, traffic, remote assistance, and correlated failures are measured"],
            ["Scale decision", "Cost per useful task and operational risk beat the best simpler alternative"],
          ],
        },
      ],
    },
    {
      heading: "22. The Next Anatomy",
      paragraphs: [
        "Humanoid design is converging on a small set of contested choices rather than one universal body. High ratio precision joints compete with lower ratio force transparent joints. Rotary cartridges compete with linear muscle architectures. Hard industrial shells compete with soft consumer bodies. Swappable batteries compete with autonomous opportunity charging. Merchant AI modules compete with custom silicon. Fully actuated hands compete with robust underactuated grippers.",
        "The near term bottlenecks are physical. High force roller screws, precision reducers, torque dense motors, durable touch, flex tolerant harnesses, safe high power packs, fast calibration, and serviceable hands have to reach automotive style repetition without automotive style volumes. Supply chain depth will matter as much as model intelligence.",
        "The strongest platform may not be the one with the highest peak torque, most degrees of freedom, or largest AI number. It may be the one whose bearings, cables, soles, seals, battery modules, and joint cartridges survive thousands of ordinary cycles with predictable maintenance. Intelligence makes the robot capable. Anatomy makes the capability available every day.",
      ],
    },
    {
      heading: "Black Scarab Takeaway",
      paragraphs: [
        "A humanoid is best understood as a moving network of electromechanical organs. The actuator is an integrated muscle and joint. The hand is a miniature robot. The foot is a changing contact model. The battery is a structural, thermal, electrical, and safety system. The GPU sits at the top of a hierarchy, not at the center of every reflex. The cable harness is a reliability system. The skin is both protection and service hardware.",
        "The component opportunity is therefore much larger than the visible robot brands. Motors, reducers, bearings, screws, encoders, drives, cells, BMS silicon, connectors, cameras, lidar, IMUs, force sensors, tactile arrays, thermal materials, safety controls, contract manufacturing, calibration, and spare logistics all become part of the market.",
        "The discipline is to follow evidence. A product page proves capability, not customer adoption. A partnership proves a relationship, not the exact production bill of materials. An in house claim proves architectural control, not self sufficiency. That careful anatomy is what lets investors, operators, suppliers, and buyers see the humanoid industry as it actually is.",
      ],
    },
    {
      heading: "Sourcing and Verification",
      paragraphs: [
        "This guide was compiled from official robot product pages, engineering updates, technical documentation, supplier product materials, public manufacturing announcements, safety references, and disclosed commercial relationships available through September 7, 2026. Platform specifications, component options, supplier relationships, certification scope, pricing, and availability can change by generation and configuration. Verify current details directly with the robot maker and component supplier before engineering, investment, or procurement decisions.",
        "All anatomy images are original Black Scarab editorial illustrations. They synthesize common engineering architectures to make the systems understandable. They do not reveal or claim the confidential internal layout of any named commercial robot.",
      ],
    },
  ],
  sources: [
    "Figure 03 engineering and battery materials",
    "Boston Dynamics Atlas product and engineering materials",
    "Agility Robotics Digit product, safety, and deployment materials",
    "Unitree G1 and H1 product and developer materials",
    "Apptronik Apollo product and manufacturing materials",
    "1X NEO product and engineering materials",
    "PAL Robotics TALOS and Kangaroo technical materials",
    "NVIDIA Jetson Thor product and humanoid reference materials",
    "Schaeffler humanoid motion portfolio and partnerships",
    "Supplier technical documentation listed below",
  ],
  sourceLinks: [
    { label: "Figure 03 architecture", url: "https://www.figure.ai/news/introducing-figure-03?id=Figure03" },
    { label: "Figure F.03 battery development", url: "https://www.figure.ai/news/f-03-battery-development" },
    { label: "Figure Helix 02 control architecture", url: "https://www.figure.ai/news/helix-02" },
    { label: "Figure BMW production lessons", url: "https://www.figure.ai/news/production-at-bmw" },
    { label: "Boston Dynamics Atlas", url: "https://bostondynamics.com/products/atlas/" },
    { label: "Atlas specification sheet", url: "https://bostondynamics.com/wp-content/uploads/2026/01/atlas-spec-sheet.pdf" },
    { label: "Atlas design engineering webinar", url: "https://bostondynamics.com/webinars/form-function-enterprise-humanoid-design/" },
    { label: "Agility Robotics Digit safety", url: "https://www.agilityrobotics.com/content/agility-robotics-announces-new-innovations-for-market-leading-humanoid-robot-digit" },
    { label: "Agility Digit simulation and feet", url: "https://www.agilityrobotics.com/content/crossing-sim2real-gap-with-isaaclab" },
    { label: "Agility and Vibram", url: "https://www.agilityrobotics.com/videos/vibram-x-agility-robotics" },
    { label: "Unitree G1", url: "https://www.unitree.com/g1/" },
    { label: "Unitree H1", url: "https://www.unitree.com/h1/" },
    { label: "Unitree sensor device repository", url: "https://github.com/unitreerobotics/xr_teleoperate/blob/main/Device.md" },
    { label: "Apptronik Apollo 2", url: "https://apptronik.com/apollo/apollo-2" },
    { label: "Jabil and Apptronik", url: "https://www.jabil.com/news/apptronik-jabil-collaborate.html" },
    { label: "1X NEO system", url: "https://www.1x.tech/discover/neo-home-robot" },
    { label: "1X NEO hands", url: "https://www.1x.tech/discover/neos-hands" },
    { label: "PAL Robotics TALOS", url: "https://pal-robotics.com/robot/talos/" },
    { label: "NVIDIA Jetson Thor", url: "https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-thor/" },
    { label: "NVIDIA humanoid reference design", url: "https://nvidianews.nvidia.com/news/nvidia-open-humanoid-robot-reference-design" },
    { label: "Schaeffler humanoid robot portfolio", url: "https://www.schaeffler.com/en/technology-innovation/technology/humanoid-robots/" },
    { label: "Schaeffler and Humanoid partnership", url: "https://www.schaeffler.com/en/investor-relations/events-publications/ir-releases/ir_releases_detail.jsp?id=88159810" },
    { label: "maxon and Reachy 2", url: "https://www.maxongroup.com/en-us/knowledge-and-support/blog/reachy-2-the-open-source-humanoid-robot-257768" },
    { label: "Harmonic Drive actuator anatomy", url: "https://www.harmonicdrive.net/media/3290/how-to-build-better-robotics-with-integrated-actuators.pdf" },
    { label: "Synapticon humanoid motion systems", url: "https://www.synapticon.com/en/applications/humanoids" },
    { label: "Renishaw encoder solutions for robotics", url: "https://info.renishaw.com/Encoders-Robotics" },
    { label: "TI humanoid design resources", url: "https://www.ti.com/applications/industrial/robotics/humanoid-robot/overview.html" },
    { label: "RealSense D455 depth camera", url: "https://www.realsenseai.com/products/real-sense-depth-camera-d455f/" },
    { label: "Stereolabs ZED X Mini", url: "https://store.stereolabs.com/products/zed-x-mini-stereo-camera" },
    { label: "Ouster and FieldAI", url: "https://investors.ouster.com/news-releases/news-release-details/ouster-and-fieldai-collaborate-scale-autonomous-perception" },
    { label: "ATI force torque sensors", url: "https://www.ati-ia.com/Products/ft/sensors.aspx" },
    { label: "GelSight robotics tactile sensors", url: "https://www.gelsight.com/products/" },
    { label: "Shadow Robot Dexterous Hand", url: "https://shadowrobot.com/dexterous-hand-series/" },
    { label: "Molex humanoid interconnect guide", url: "https://www.molex.com/en-us/industries-applications/humanoid-robotics/humanoid-robotics-connectors" },
    { label: "TE Connectivity humanoid components", url: "https://www.te.com/en/about-te/news-center/media-resources/trends-or-topic-subject-matter-expert/humanoid-robots.html" },
    { label: "igus robotic cables", url: "https://www.igus.com/cables/robotic-cables" },
    { label: "Molicel high power P45B cell", url: "https://www.molicel.com/inr-21700-p45b/" },
    { label: "CATL and Galbot S1", url: "https://www.catl.com/en/news/6881.html" },
    { label: "ISO robotics standards overview", url: "https://www.iso.org/cms/live/live/en/sites/isoorg/home/sectors/engineering/robotics.html" },
  ],
});
